name: kuwboo_web
description: Kuwboo web application
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.11.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  kuwboo_ui:
    path: ../../packages/ui
  kuwboo_shell:
    path: ../../packages/kuwboo_shell
  kuwboo_screens:
    path: ../../packages/kuwboo_screens
  kuwboo_chat:
    path: ../../packages/kuwboo_chat
  google_fonts: ^8.0.0
  phosphor_flutter: ^2.1.0
  lucide_icons_flutter: ^3.1.10
  heroicons_flutter: ^0.4.0
  iconsax_flutter: ^1.0.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
