name: kuwboo_api_client
description: Kuwboo API client with Dio HTTP and auth interceptor
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.11.1

resolution: workspace

dependencies:
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.0
  kuwboo_models:
    path: ../models

dependency_overrides: {}
