name: kuwboo_workspace
publish_to: 'none'

environment:
  sdk: ^3.11.1

workspace:
  - apps/web
  - apps/mobile
  - packages/models
  - packages/api_client
  - packages/kuwboo_shell
  - packages/kuwboo_screens
  - packages/kuwboo_chat
  - packages/kuwboo_auth
