import { Migration } from '@mikro-orm/migrations';

/**
 * Baseline schema migration.
 *
 * Captures the full entity graph as it existed on RDS after months of
 * `schema:update --run` drift. From this point forward, all schema changes
 * MUST go through generated migrations (`mikro-orm migration:create`).
 *
 * On the live RDS instance, this migration is marked as already-executed
 * (the tables it creates already exist there). On a fresh DB it runs
 * normally to produce the same schema.
 *
 * Replaces the orphaned migrations: add_admin_audit_log, add_bots, apple_s2s
 * — those tables are now part of this baseline.
 */
export class Migration20260413BaselineSchema extends Migration {
  override async up(): Promise<void> {
    this.addSql(`create table "audio_tracks" ("id" uuid not null, "title" varchar(255) not null, "artist_name" varchar(255) not null, "url" varchar(1024) not null, "duration_seconds" int not null, "usage_count" int not null default 0, "is_original" boolean not null default false, "source_video_id" uuid null, "created_at" timestamptz not null default now(), constraint "audio_tracks_pkey" primary key ("id"));`);
    this.addSql(`create table "categories" ("id" uuid not null, "name" varchar(100) not null, "slug" varchar(100) not null, "scope" text check ("scope" in ('VIDEO', 'PRODUCT', 'POST')) not null, "icon_url" varchar(512) null, "sort_order" int not null default 0, "is_active" boolean not null default true, "parent_id" uuid null, "created_at" timestamptz not null default now(), constraint "categories_pkey" primary key ("id"));`);
    this.addSql(`alter table "categories" add constraint "categories_slug_unique" unique ("slug");`);
    this.addSql(`create table "tags" ("id" uuid not null, "name" varchar(50) not null, "usage_count" int not null default 0, "created_at" timestamptz not null default now(), constraint "tags_pkey" primary key ("id"));`);
    this.addSql(`alter table "tags" add constraint "tags_name_unique" unique ("name");`);
    this.addSql(`create table "threads" ("id" uuid not null, "module_key" text check ("module_key" in ('VIDEO_MAKING', 'BUY_SELL', 'DATING', 'SOCIAL_STUMBLE', 'YOYO')) null, "context_id" uuid null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), constraint "threads_pkey" primary key ("id"));`);
    this.addSql(`create table "users" ("id" uuid not null, "phone" varchar(20) null, "email" varchar(255) null, "name" varchar(100) not null, "avatar_url" varchar(512) null, "date_of_birth" date null, "role" text check ("role" in ('USER', 'MODERATOR', 'ADMIN', 'SUPER_ADMIN')) not null default 'USER', "status" text check ("status" in ('ACTIVE', 'SUSPENDED', 'BANNED', 'DELETED')) not null default 'ACTIVE', "last_location" geography(Point, 4326) null, "online_status" text check ("online_status" in ('ONLINE', 'AWAY', 'OFFLINE')) not null default 'OFFLINE', "password_hash" varchar(255) null, "google_id" varchar(255) null, "apple_id" varchar(255) null, "apple_email_is_private_relay" boolean not null default false, "apple_consent_revoked_at" timestamptz null, "apple_account_deleted_at" timestamptz null, "is_bot" boolean not null default false, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, constraint "users_pkey" primary key ("id"));`);
    this.addSql(`alter table "users" add constraint "users_phone_unique" unique ("phone");`);
    this.addSql(`alter table "users" add constraint "users_email_unique" unique ("email");`);
    this.addSql(`alter table "users" add constraint "users_google_id_unique" unique ("google_id");`);
    this.addSql(`alter table "users" add constraint "users_apple_id_unique" unique ("apple_id");`);
    this.addSql(`create index "users_is_bot_index" on "users" ("is_bot");`);
    this.addSql(`create index "users_status_index" on "users" ("status");`);
    this.addSql(`create table "thread_participants" ("id" uuid not null, "thread_id" uuid not null, "user_id" uuid not null, "last_read_at" timestamptz null, "joined_at" timestamptz not null default now(), constraint "thread_participants_pkey" primary key ("id"));`);
    this.addSql(`alter table "thread_participants" add constraint "thread_participants_thread_id_user_id_unique" unique ("thread_id", "user_id");`);
    this.addSql(`create table "sessions" ("id" uuid not null, "user_id" uuid not null, "refresh_token_hash" varchar(255) not null, "user_agent" varchar(255) null, "ip_address" varchar(45) null, "expires_at" timestamptz not null, "is_revoked" boolean not null default false, "provider" varchar(20) null, "provider_identifier" varchar(255) null, "revoke_reason" varchar(100) null, "created_at" timestamptz not null default now(), constraint "sessions_pkey" primary key ("id"));`);
    this.addSql(`create index "sessions_provider_provider_identifier_index" on "sessions" ("provider", "provider_identifier");`);
    this.addSql(`create table "notification_preferences" ("id" uuid not null, "user_id" uuid not null, "module_key" varchar(50) not null, "event_type" varchar(50) not null, "push_enabled" boolean not null default true, "in_app_enabled" boolean not null default true, "created_at" timestamptz not null default now(), constraint "notification_preferences_pkey" primary key ("id"));`);
    this.addSql(`alter table "notification_preferences" add constraint "notification_preferences_user_id_module_key_event_type_unique" unique ("user_id", "module_key", "event_type");`);
    this.addSql(`create table "notifications" ("id" uuid not null, "user_id" uuid not null, "type" text check ("type" in ('NEW_FOLLOWER', 'LIKE', 'COMMENT', 'MENTION', 'MESSAGE', 'FRIEND_REQUEST', 'FRIEND_ACCEPTED', 'BID_PLACED', 'BID_OUTBID', 'AUCTION_WON', 'AUCTION_ENDED', 'CONTENT_APPROVED', 'CONTENT_REMOVED', 'SYSTEM')) not null, "title" varchar(255) not null, "body" text not null, "data" jsonb null, "group_key" varchar(100) null, "read_at" timestamptz null, "created_at" timestamptz not null default now(), constraint "notifications_pkey" primary key ("id"));`);
    this.addSql(`create index "notifications_user_id_read_at_index" on "notifications" ("user_id", "read_at");`);
    this.addSql(`create table "messages" ("id" uuid not null, "thread_id" uuid not null, "sender_id" uuid not null, "text" text not null, "media_id" uuid null, "created_at" timestamptz not null default now(), constraint "messages_pkey" primary key ("id"));`);
    this.addSql(`create index "messages_thread_id_created_at_index" on "messages" ("thread_id", "created_at");`);
    this.addSql(`create table "media" ("id" uuid not null, "uploader_id" uuid not null, "url" varchar(1024) null, "thumbnail_url" varchar(1024) null, "type" text check ("type" in ('IMAGE', 'VIDEO', 'AUDIO')) not null, "status" text check ("status" in ('PROCESSING', 'READY', 'FAILED')) not null default 'PROCESSING', "mime_type" varchar(100) not null, "size_bytes" bigint not null, "duration_seconds" int null, "width" int null, "height" int null, "s3key" varchar(1024) not null, "s3bucket" varchar(255) not null, "created_at" timestamptz not null default now(), constraint "media_pkey" primary key ("id"));`);
    this.addSql(`create table "devices" ("id" uuid not null, "user_id" uuid not null, "fcm_token" varchar(512) not null, "platform" text check ("platform" in ('IOS', 'ANDROID')) not null, "app_version" varchar(20) null, "device_model" varchar(100) null, "os_version" varchar(20) null, "is_active" boolean not null default true, "last_active_at" timestamptz not null default now(), "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), constraint "devices_pkey" primary key ("id"));`);
    this.addSql(`alter table "devices" add constraint "devices_fcm_token_unique" unique ("fcm_token");`);
    this.addSql(`create table "content" ("id" uuid not null, "type" text check ("type" in ('VIDEO', 'PRODUCT', 'POST', 'EVENT', 'WANTED_AD')) not null, "creator_id" uuid not null, "visibility" text check ("visibility" in ('PUBLIC', 'CONNECTIONS', 'PRIVATE')) not null default 'PUBLIC', "tier" text check ("tier" in ('FREE', 'MEMBER', 'VIP', 'BOOSTED')) not null default 'FREE', "location" geography(Point, 4326) null, "location_name" varchar(255) null, "like_count" int not null default 0, "save_count" int not null default 0, "share_count" int not null default 0, "view_count" int not null default 0, "comment_count" int not null default 0, "status" text check ("status" in ('PENDING', 'ACTIVE', 'HIDDEN', 'FLAGGED', 'REMOVED')) not null default 'PENDING', "boost_expires_at" timestamptz null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, "sub_type" text check ("sub_type" in ('STANDARD', 'BLOG', 'NOTICE', 'MISSING_PERSON')) null default 'STANDARD', "text" text null, "is_pinned" boolean null default false, "reading_time" varchar(50) null, "title" varchar(255) null, "description" text null, "price_cents" int null, "currency" varchar(3) null default 'GBP', "condition" text check ("condition" in ('NEW', 'LIKE_NEW', 'GOOD', 'FAIR', 'FOR_PARTS')) null, "is_deal" boolean null default false, "original_price_cents" int null, "video_url" varchar(1024) null, "thumbnail_url" varchar(1024) null, "duration_seconds" int null, "caption" text null, "music_id" uuid null, constraint "content_pkey" primary key ("id"));`);
    this.addSql(`create index "content_type_index" on "content" ("type");`);
    this.addSql(`create index "content_status_type_created_at_index" on "content" ("status", "type", "created_at");`);
    this.addSql(`create table "sponsored_campaigns" ("id" uuid not null, "advertiser_id" uuid not null, "content_id" uuid not null, "budget_cents" int not null, "spent_cents" int not null default 0, "status" text check ("status" in ('DRAFT', 'ACTIVE', 'PAUSED', 'ENDED')) not null default 'DRAFT', "targeting" jsonb null, "starts_at" timestamptz not null, "ends_at" timestamptz not null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), constraint "sponsored_campaigns_pkey" primary key ("id"));`);
    this.addSql(`create table "seller_ratings" ("id" uuid not null, "seller_id" uuid not null, "buyer_id" uuid not null, "product_id" uuid not null, "rating" smallint not null, "review" text null, "created_at" timestamptz not null default now(), constraint "seller_ratings_pkey" primary key ("id"));`);
    this.addSql(`alter table "seller_ratings" add constraint "seller_ratings_buyer_id_product_id_unique" unique ("buyer_id", "product_id");`);
    this.addSql(`create table "interaction_states" ("id" uuid not null, "user_id" uuid not null, "content_id" uuid not null, "type" text check ("type" in ('LIKE', 'SAVE')) not null, "created_at" timestamptz not null default now(), constraint "interaction_states_pkey" primary key ("id"));`);
    this.addSql(`alter table "interaction_states" add constraint "interaction_states_user_id_content_id_type_unique" unique ("user_id", "content_id", "type");`);
    this.addSql(`create table "interaction_events" ("id" uuid not null, "user_id" uuid not null, "content_id" uuid not null, "type" text check ("type" in ('VIEW', 'SHARE', 'BID', 'SWIPE_RIGHT', 'SWIPE_LEFT', 'SUPER_LIKE', 'SPARK')) not null, "metadata" jsonb null, "created_at" timestamptz not null default now(), constraint "interaction_events_pkey" primary key ("id"));`);
    this.addSql(`create index "interaction_events_content_id_created_at_index" on "interaction_events" ("content_id", "created_at");`);
    this.addSql(`create table "content_tags" ("id" uuid not null, "content_id" uuid not null, "tag_id" uuid not null, constraint "content_tags_pkey" primary key ("id"));`);
    this.addSql(`alter table "content_tags" add constraint "content_tags_content_id_tag_id_unique" unique ("content_id", "tag_id");`);
    this.addSql(`create table "auctions" ("id" uuid not null, "product_id" uuid not null, "start_price_cents" int not null, "current_price_cents" int not null, "min_increment_cents" int not null default 100, "starts_at" timestamptz not null, "ends_at" timestamptz not null, "status" text check ("status" in ('SCHEDULED', 'ACTIVE', 'ENDED', 'CANCELLED')) not null default 'SCHEDULED', "winner_id" uuid null, "anti_snipe_minutes" int not null default 2, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), constraint "auctions_pkey" primary key ("id"));`);
    this.addSql(`alter table "auctions" add constraint "auctions_product_id_unique" unique ("product_id");`);
    this.addSql(`create index "auctions_status_ends_at_index" on "auctions" ("status", "ends_at");`);
    this.addSql(`create table "connections" ("id" uuid not null, "from_user_id" uuid not null, "to_user_id" uuid not null, "context" text check ("context" in ('FOLLOW', 'FRIEND', 'MATCH', 'YOYO')) not null, "status" text check ("status" in ('PENDING', 'ACTIVE', 'REJECTED')) not null default 'ACTIVE', "module_scope" text check ("module_scope" in ('VIDEO', 'SOCIAL', 'SHOP', 'DATING')) null, "confirmed_at" timestamptz null, "created_at" timestamptz not null default now(), constraint "connections_pkey" primary key ("id"));`);
    this.addSql(`create index "connections_to_user_id_context_index" on "connections" ("to_user_id", "context");`);
    this.addSql(`create index "connections_from_user_id_context_index" on "connections" ("from_user_id", "context");`);
    this.addSql(`alter table "connections" add constraint "connections_from_user_id_to_user_id_context_module_scope_unique" unique ("from_user_id", "to_user_id", "context", "module_scope");`);
    this.addSql(`create table "comments" ("id" uuid not null, "content_id" uuid not null, "author_id" uuid not null, "text" text not null, "like_count" int not null default 0, "reply_count" int not null default 0, "parent_comment_id" uuid null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, constraint "comments_pkey" primary key ("id"));`);
    this.addSql(`create index "comments_content_id_created_at_index" on "comments" ("content_id", "created_at");`);
    this.addSql(`create table "reports" ("id" uuid not null, "reporter_id" uuid not null, "target_type" text check ("target_type" in ('CONTENT', 'USER', 'COMMENT', 'MESSAGE')) not null, "reported_content_id" uuid null, "reported_user_id" uuid null, "reported_comment_id" uuid null, "reason" text check ("reason" in ('SPAM', 'ABUSE', 'ILLEGAL', 'INAPPROPRIATE', 'MISLEADING', 'COPYRIGHT')) not null, "description" text null, "status" text check ("status" in ('PENDING', 'IN_REVIEW', 'DISMISSED', 'RESOLVED', 'ESCALATED')) not null default 'PENDING', "reviewed_by" uuid null, "review_notes" text null, "created_at" timestamptz not null default now(), "reviewed_at" timestamptz null, constraint "reports_pkey" primary key ("id"));`);
    this.addSql(`create index "reports_status_created_at_index" on "reports" ("status", "created_at");`);
    this.addSql(`create table "bot_profiles" ("id" uuid not null, "user_id" uuid not null, "display_persona" varchar(50) not null, "backstory" text null, "behavior_config" jsonb not null, "simulation_status" text check ("simulation_status" in ('IDLE', 'RUNNING', 'PAUSED', 'ERROR')) not null default 'IDLE', "home_location" geography(Point, 4326) null, "roam_radius_km" int not null default 5, "last_simulated_at" timestamptz null, "total_actions" int not null default 0, "error_message" varchar(255) null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), constraint "bot_profiles_pkey" primary key ("id"));`);
    this.addSql(`alter table "bot_profiles" add constraint "bot_profiles_user_id_unique" unique ("user_id");`);
    this.addSql(`create index "bot_profiles_simulation_status_index" on "bot_profiles" ("simulation_status");`);
    this.addSql(`create table "bot_activity_logs" ("id" uuid not null, "bot_profile_id" uuid not null, "action_type" varchar(50) not null, "target_id" uuid null, "metadata" jsonb null, "success" boolean not null default true, "error_message" varchar(255) null, "executed_at" timestamptz not null default now(), constraint "bot_activity_logs_pkey" primary key ("id"));`);
    this.addSql(`create index "bot_activity_logs_bot_profile_id_executed_at_index" on "bot_activity_logs" ("bot_profile_id", "executed_at");`);
    this.addSql(`create table "blocks" ("id" uuid not null, "blocker_id" uuid not null, "blocked_id" uuid not null, "created_at" timestamptz not null default now(), constraint "blocks_pkey" primary key ("id"));`);
    this.addSql(`create index "blocks_blocked_id_index" on "blocks" ("blocked_id");`);
    this.addSql(`create index "blocks_blocker_id_index" on "blocks" ("blocker_id");`);
    this.addSql(`alter table "blocks" add constraint "blocks_blocker_id_blocked_id_unique" unique ("blocker_id", "blocked_id");`);
    this.addSql(`create table "bids" ("id" uuid not null, "auction_id" uuid not null, "bidder_id" uuid not null, "amount_cents" int not null, "created_at" timestamptz not null default now(), constraint "bids_pkey" primary key ("id"));`);
    this.addSql(`create table "apple_notification_events" ("id" uuid not null, "jti" varchar(64) not null, "event_type" text check ("event_type" in ('account-delete', 'consent-revoked', 'email-disabled', 'email-enabled')) not null, "apple_sub" varchar(255) not null, "apple_event_time" timestamptz not null, "user_id" uuid null, "signature_valid" boolean not null default true, "raw_payload_sha256" varchar(64) not null, "claims" jsonb not null, "event_payload" jsonb not null, "source_ip" varchar(45) null, "user_agent" varchar(255) null, "processed_at" timestamptz null, "processing_error" text null, "processing_attempts" int not null default 0, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), constraint "apple_notification_events_pkey" primary key ("id"));`);
    this.addSql(`alter table "apple_notification_events" add constraint "apple_notification_events_jti_unique" unique ("jti");`);
    this.addSql(`create index "apple_notification_events_apple_event_time_index" on "apple_notification_events" ("apple_event_time");`);
    this.addSql(`create index "apple_notification_events_user_id_index" on "apple_notification_events" ("user_id");`);
    this.addSql(`create index "apple_notification_events_apple_sub_index" on "apple_notification_events" ("apple_sub");`);
    this.addSql(`create index "apple_notification_events_event_type_processed_at_index" on "apple_notification_events" ("event_type", "processed_at");`);
    this.addSql(`create table "admin_audit_logs" ("id" uuid not null, "admin_user_id" uuid null, "actor_type" varchar(20) not null default 'admin', "action_type" varchar(50) not null, "target_type" varchar(50) not null, "target_id" uuid null, "details" jsonb null, "ip_address" varchar(45) null, "created_at" timestamptz not null default now(), constraint "admin_audit_logs_pkey" primary key ("id"));`);
    this.addSql(`create index "admin_audit_logs_admin_user_id_created_at_index" on "admin_audit_logs" ("admin_user_id", "created_at");`);
    this.addSql(`create table "user_consents" ("id" uuid not null, "user_id" uuid not null, "consent_type" text check ("consent_type" in ('TERMS', 'PRIVACY', 'MARKETING', 'LOCATION', 'COOKIES', 'DATA_SALE_OPT_OUT')) not null, "version" varchar(20) not null, "source" text check ("source" in ('REGISTRATION', 'SETTINGS', 'PROMPT', 'LEGAL_UPDATE')) not null, "granted_at" timestamptz not null default now(), "revoked_at" timestamptz null, "ip_address" varchar(45) null, constraint "user_consents_pkey" primary key ("id"));`);
    this.addSql(`alter table "user_consents" add constraint "user_consents_user_id_consent_type_version_unique" unique ("user_id", "consent_type", "version");`);
    this.addSql(`create table "user_preferences" ("id" uuid not null, "user_id" uuid not null, "notifications" jsonb not null, "privacy" jsonb not null, "feed_weights" jsonb null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), constraint "user_preferences_pkey" primary key ("id"));`);
    this.addSql(`alter table "user_preferences" add constraint "user_preferences_user_id_unique" unique ("user_id");`);
    this.addSql(`create table "verifications" ("id" uuid not null, "identifier" varchar(255) not null, "code_hash" varchar(255) not null, "type" text check ("type" in ('PHONE_OTP', 'EMAIL_VERIFY', 'PASSWORD_RESET')) not null, "expires_at" timestamptz not null, "attempts" int not null default 0, "verified_at" timestamptz null, "created_at" timestamptz not null default now(), constraint "verifications_pkey" primary key ("id"));`);
    this.addSql(`create index "verifications_identifier_type_index" on "verifications" ("identifier", "type");`);
    this.addSql(`create table "waves" ("id" uuid not null, "from_user_id" uuid not null, "to_user_id" uuid not null, "message" varchar(255) null, "status" text check ("status" in ('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED')) not null default 'PENDING', "created_at" timestamptz not null default now(), "responded_at" timestamptz null, constraint "waves_pkey" primary key ("id"));`);
    this.addSql(`create index "waves_to_user_id_status_index" on "waves" ("to_user_id", "status");`);
    this.addSql(`create table "yoyo_overrides" ("id" uuid not null, "user_id" uuid not null, "target_user_id" uuid not null, "action" text check ("action" in ('ALLOW', 'BLOCK')) not null, "created_at" timestamptz not null default now(), constraint "yoyo_overrides_pkey" primary key ("id"));`);
    this.addSql(`alter table "yoyo_overrides" add constraint "yoyo_overrides_user_id_target_user_id_unique" unique ("user_id", "target_user_id");`);
    this.addSql(`create table "yoyo_settings" ("id" uuid not null, "user_id" uuid not null, "is_visible" boolean not null default true, "radius_km" int not null default 10, "age_min" int null, "age_max" int null, "gender_filter" varchar(20) null, "show_in_modules" jsonb null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), constraint "yoyo_settings_pkey" primary key ("id"));`);
    this.addSql(`alter table "yoyo_settings" add constraint "yoyo_settings_user_id_unique" unique ("user_id");`);
    this.addSql(`alter table "categories" add constraint "categories_parent_id_foreign" foreign key ("parent_id") references "categories" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "thread_participants" add constraint "thread_participants_thread_id_foreign" foreign key ("thread_id") references "threads" ("id") on update cascade;`);
    this.addSql(`alter table "thread_participants" add constraint "thread_participants_user_id_foreign" foreign key ("user_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "sessions" add constraint "sessions_user_id_foreign" foreign key ("user_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "notification_preferences" add constraint "notification_preferences_user_id_foreign" foreign key ("user_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "notifications" add constraint "notifications_user_id_foreign" foreign key ("user_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "messages" add constraint "messages_thread_id_foreign" foreign key ("thread_id") references "threads" ("id") on update cascade;`);
    this.addSql(`alter table "messages" add constraint "messages_sender_id_foreign" foreign key ("sender_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "media" add constraint "media_uploader_id_foreign" foreign key ("uploader_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "devices" add constraint "devices_user_id_foreign" foreign key ("user_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "content" add constraint "content_creator_id_foreign" foreign key ("creator_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "sponsored_campaigns" add constraint "sponsored_campaigns_advertiser_id_foreign" foreign key ("advertiser_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "sponsored_campaigns" add constraint "sponsored_campaigns_content_id_foreign" foreign key ("content_id") references "content" ("id") on update cascade;`);
    this.addSql(`alter table "seller_ratings" add constraint "seller_ratings_seller_id_foreign" foreign key ("seller_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "seller_ratings" add constraint "seller_ratings_buyer_id_foreign" foreign key ("buyer_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "seller_ratings" add constraint "seller_ratings_product_id_foreign" foreign key ("product_id") references "content" ("id") on update cascade;`);
    this.addSql(`alter table "interaction_states" add constraint "interaction_states_user_id_foreign" foreign key ("user_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "interaction_states" add constraint "interaction_states_content_id_foreign" foreign key ("content_id") references "content" ("id") on update cascade;`);
    this.addSql(`alter table "interaction_events" add constraint "interaction_events_user_id_foreign" foreign key ("user_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "interaction_events" add constraint "interaction_events_content_id_foreign" foreign key ("content_id") references "content" ("id") on update cascade;`);
    this.addSql(`alter table "content_tags" add constraint "content_tags_content_id_foreign" foreign key ("content_id") references "content" ("id") on update cascade;`);
    this.addSql(`alter table "content_tags" add constraint "content_tags_tag_id_foreign" foreign key ("tag_id") references "tags" ("id") on update cascade;`);
    this.addSql(`alter table "auctions" add constraint "auctions_product_id_foreign" foreign key ("product_id") references "content" ("id") on update cascade;`);
    this.addSql(`alter table "connections" add constraint "connections_from_user_id_foreign" foreign key ("from_user_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "connections" add constraint "connections_to_user_id_foreign" foreign key ("to_user_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "comments" add constraint "comments_content_id_foreign" foreign key ("content_id") references "content" ("id") on update cascade;`);
    this.addSql(`alter table "comments" add constraint "comments_author_id_foreign" foreign key ("author_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "comments" add constraint "comments_parent_comment_id_foreign" foreign key ("parent_comment_id") references "comments" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "reports" add constraint "reports_reporter_id_foreign" foreign key ("reporter_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "reports" add constraint "reports_reported_content_id_foreign" foreign key ("reported_content_id") references "content" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "reports" add constraint "reports_reported_user_id_foreign" foreign key ("reported_user_id") references "users" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "reports" add constraint "reports_reported_comment_id_foreign" foreign key ("reported_comment_id") references "comments" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "bot_profiles" add constraint "bot_profiles_user_id_foreign" foreign key ("user_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "bot_activity_logs" add constraint "bot_activity_logs_bot_profile_id_foreign" foreign key ("bot_profile_id") references "bot_profiles" ("id") on update cascade;`);
    this.addSql(`alter table "blocks" add constraint "blocks_blocker_id_foreign" foreign key ("blocker_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "blocks" add constraint "blocks_blocked_id_foreign" foreign key ("blocked_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "bids" add constraint "bids_auction_id_foreign" foreign key ("auction_id") references "auctions" ("id") on update cascade;`);
    this.addSql(`alter table "bids" add constraint "bids_bidder_id_foreign" foreign key ("bidder_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "apple_notification_events" add constraint "apple_notification_events_user_id_foreign" foreign key ("user_id") references "users" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "admin_audit_logs" add constraint "admin_audit_logs_admin_user_id_foreign" foreign key ("admin_user_id") references "users" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "user_consents" add constraint "user_consents_user_id_foreign" foreign key ("user_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "user_preferences" add constraint "user_preferences_user_id_foreign" foreign key ("user_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "waves" add constraint "waves_from_user_id_foreign" foreign key ("from_user_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "waves" add constraint "waves_to_user_id_foreign" foreign key ("to_user_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "yoyo_overrides" add constraint "yoyo_overrides_user_id_foreign" foreign key ("user_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "yoyo_overrides" add constraint "yoyo_overrides_target_user_id_foreign" foreign key ("target_user_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "yoyo_settings" add constraint "yoyo_settings_user_id_foreign" foreign key ("user_id") references "users" ("id") on update cascade;`);

  }

  override async down(): Promise<void> {
    throw new Error('Baseline schema migration cannot be rolled back');
  }
}
