import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:phosphor_flutter/phosphor_flutter.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';
import 'package:heroicons_flutter/heroicons_flutter.dart';
import 'package:iconsax_flutter/iconsax_flutter.dart';

/// A toggle pair: inactive (outlined) and active (filled) variants of an icon.
/// Used for bottom nav tabs and service FAB icons that change on selection.
class ToggleIcon {
  final IconData inactive;
  final IconData active;
  const ToggleIcon(this.inactive, this.active);
}

/// A complete icon set that can be swapped across the entire prototype.
///
/// Icons are split into three usage categories:
///   A) Nav toggle pairs — bottom nav tabs + service FAB icons (ToggleIcon)
///   B) UI action icons — search, share, settings, etc. (IconData)
///   C) Semantic/content — interest badges, decorative (NOT swapped, stay _rounded)
///
/// Only categories A and B are represented here. Category C icons remain
/// hardcoded in their screens because they're content identifiers, not UI chrome.
class ProtoIconSet {
  final String name;
  final String shortName;
  final String description;

  // ─── A: Nav Toggle Pairs (bottom nav tabs) ───────────────────────────

  // Video module tabs
  final ToggleIcon videoForYou;
  final ToggleIcon videoFollowing;
  final ToggleIcon videoDiscover;
  final ToggleIcon videoCreate;

  // Dating module tabs
  final ToggleIcon datingDiscover;
  final ToggleIcon datingMatches;
  final ToggleIcon datingLikes;
  final ToggleIcon datingChat;

  // YoYo module tabs
  final ToggleIcon yoyoNearby;
  final ToggleIcon yoyoConnect;
  final ToggleIcon yoyoWave;
  final ToggleIcon yoyoChat;

  // Social module tabs
  final ToggleIcon socialStumble;
  final ToggleIcon socialFriends;
  final ToggleIcon socialEvents;
  final ToggleIcon socialPost;

  // Shop module tabs
  final ToggleIcon shopBrowse;
  final ToggleIcon shopDeals;
  final ToggleIcon shopSell;
  final ToggleIcon shopMessages;

  // Service FAB icons (active = filled, inactive = outlined)
  final ToggleIcon serviceVideo;
  final ToggleIcon serviceDating;
  final ToggleIcon serviceYoyo;
  final ToggleIcon serviceSocial;
  final ToggleIcon serviceShop;

  // ─── B: UI Action Icons (single IconData) ────────────────────────────

  // Navigation & chrome
  final IconData search;
  final IconData close;
  final IconData arrowBack;
  final IconData chevronRight;
  final IconData check;
  final IconData checkCircle;
  final IconData moreHoriz;

  // Social actions
  final IconData share;
  final IconData send;
  final IconData reply;

  // Toggle actions (single icons — used where only one state is shown)
  final IconData favoriteOutline;
  final IconData favoriteFilled;
  final IconData bookmarkOutline;
  final IconData bookmarkFilled;
  final IconData visibilityOn;
  final IconData visibilityOff;
  final IconData starFilled;

  // Communication
  final IconData chatBubbleOutline;
  final IconData chatOutline;
  final IconData forum;
  final IconData comment;

  // Profile & settings
  final IconData edit;
  final IconData editOutline;
  final IconData settings;
  final IconData notifications;
  final IconData notificationsOutline;
  final IconData personOutline;
  final IconData personAdd;
  final IconData personRemove;
  final IconData storefront;
  final IconData storefrontOutline;

  // Content actions
  final IconData add;
  final IconData addCircle;
  final IconData addPhoto;
  final IconData photoLibrary;

  // Camera & video
  final IconData cameraAlt;
  final IconData cameraAltOutline;
  final IconData videocam;
  final IconData flipCamera;
  final IconData timerOutline;
  final IconData timerFilled;
  final IconData flashOn;
  final IconData flashOff;
  final IconData speedOutline;
  final IconData playArrow;
  final IconData playCircleOutline;

  // Editing
  final IconData contentCut;
  final IconData textFields;
  final IconData emojiEmotions;
  final IconData filterVintage;
  final IconData tag;

  // Info & moderation
  final IconData flag;
  final IconData lockOutline;
  final IconData blockOutline;
  final IconData phoneOutline;
  final IconData emailOutline;
  final IconData locationOff;

  // Discovery & filtering
  final IconData tune;
  final IconData filterList;
  final IconData refresh;
  final IconData radar;

  // Marketplace
  final IconData localOffer;
  final IconData localOfferOutline;
  final IconData shoppingBag;
  final IconData gavel;
  final IconData localFireDepartment;
  final IconData campaign;

  // Location & social
  final IconData locationOn;
  final IconData nearMe;
  final IconData group;
  final IconData groupOutline;
  final IconData peopleOutline;
  final IconData wavingHand;

  // Misc UI
  final IconData image;
  final IconData verified;
  final IconData calendarToday;
  final IconData linkIcon;
  final IconData linkOutline;
  final IconData replay;
  final IconData height;
  final IconData schoolOutline;
  final IconData localBarOutline;
  final IconData workOutline;
  final IconData viewList;

  // Extended icons (added for screen compatibility)
  final IconData starOutline;
  final IconData messageOutline;
  final IconData apps;
  final IconData explore;
  final IconData familyRestroom;
  final IconData shield;
  final IconData darkMode;

  const ProtoIconSet({
    required this.name,
    required this.shortName,
    required this.description,
    // Nav toggles
    required this.videoForYou,
    required this.videoFollowing,
    required this.videoDiscover,
    required this.videoCreate,
    required this.datingDiscover,
    required this.datingMatches,
    required this.datingLikes,
    required this.datingChat,
    required this.yoyoNearby,
    required this.yoyoConnect,
    required this.yoyoWave,
    required this.yoyoChat,
    required this.socialStumble,
    required this.socialFriends,
    required this.socialEvents,
    required this.socialPost,
    required this.shopBrowse,
    required this.shopDeals,
    required this.shopSell,
    required this.shopMessages,
    required this.serviceVideo,
    required this.serviceDating,
    required this.serviceYoyo,
    required this.serviceSocial,
    required this.serviceShop,
    // UI action icons
    required this.search,
    required this.close,
    required this.arrowBack,
    required this.chevronRight,
    required this.check,
    required this.checkCircle,
    required this.moreHoriz,
    required this.share,
    required this.send,
    required this.reply,
    required this.favoriteOutline,
    required this.favoriteFilled,
    required this.bookmarkOutline,
    required this.bookmarkFilled,
    required this.visibilityOn,
    required this.visibilityOff,
    required this.starFilled,
    required this.chatBubbleOutline,
    required this.chatOutline,
    required this.forum,
    required this.comment,
    required this.edit,
    required this.editOutline,
    required this.settings,
    required this.notifications,
    required this.notificationsOutline,
    required this.personOutline,
    required this.personAdd,
    required this.personRemove,
    required this.storefront,
    required this.storefrontOutline,
    required this.add,
    required this.addCircle,
    required this.addPhoto,
    required this.photoLibrary,
    required this.cameraAlt,
    required this.cameraAltOutline,
    required this.videocam,
    required this.flipCamera,
    required this.timerOutline,
    required this.timerFilled,
    required this.flashOn,
    required this.flashOff,
    required this.speedOutline,
    required this.playArrow,
    required this.playCircleOutline,
    required this.contentCut,
    required this.textFields,
    required this.emojiEmotions,
    required this.filterVintage,
    required this.tag,
    required this.flag,
    required this.lockOutline,
    required this.blockOutline,
    required this.phoneOutline,
    required this.emailOutline,
    required this.locationOff,
    required this.tune,
    required this.filterList,
    required this.refresh,
    required this.radar,
    required this.localOffer,
    required this.localOfferOutline,
    required this.shoppingBag,
    required this.gavel,
    required this.localFireDepartment,
    required this.campaign,
    required this.locationOn,
    required this.nearMe,
    required this.group,
    required this.groupOutline,
    required this.peopleOutline,
    required this.wavingHand,
    required this.image,
    required this.verified,
    required this.calendarToday,
    required this.linkIcon,
    required this.linkOutline,
    required this.replay,
    required this.height,
    required this.schoolOutline,
    required this.localBarOutline,
    required this.workOutline,
    required this.viewList,
    this.starOutline = CupertinoIcons.star,
    this.messageOutline = CupertinoIcons.bubble_left,
    this.apps = CupertinoIcons.square_grid_2x2,
    this.explore = CupertinoIcons.compass,
    this.familyRestroom = Icons.family_restroom_rounded,
    this.shield = CupertinoIcons.shield,
    this.darkMode = CupertinoIcons.moon,
  });

  /// All 14 icon sets in display order.
  static const List<ProtoIconSet> all = [
    appleHIG,
    instagramSocial,
    modernOutlined,
    roundedClassic,
    sharpGeometric,
    standardFilled,
    conceptualRemix,
    minimalGlyph,
    expressiveSocial,
    technicalBlueprint,
    phosphorDuotone,
    lucideClean,
    heroiconsGeo,
    iconsaxBold,
  ];

  // ═══════════════════════════════════════════════════════════════════════
  //  Apple HIG — CupertinoIcons from Apple's SF Symbols–inspired set
  //  Key: share=square_arrow_up (iOS share sheet), clean outline/fill toggle,
  //       consistent weight, distinctive from Material's visual language
  // ═══════════════════════════════════════════════════════════════════════

  static const appleHIG = ProtoIconSet(
    name: 'Apple HIG',
    shortName: 'Apple',
    description: 'iOS-native CupertinoIcons — SF Symbols style with outline/fill toggle',
    // Video tabs — house/compass/people pattern (iOS Tab Bar style)
    videoForYou: ToggleIcon(CupertinoIcons.house, CupertinoIcons.house_fill),
    videoFollowing: ToggleIcon(CupertinoIcons.person_2, CupertinoIcons.person_2_fill),
    videoDiscover: ToggleIcon(CupertinoIcons.compass, CupertinoIcons.compass_fill),
    videoCreate: ToggleIcon(CupertinoIcons.plus_app, CupertinoIcons.plus_app_fill),
    // Dating tabs
    datingDiscover: ToggleIcon(CupertinoIcons.compass, CupertinoIcons.compass_fill),
    datingMatches: ToggleIcon(CupertinoIcons.person_2, CupertinoIcons.person_2_fill),
    datingLikes: ToggleIcon(CupertinoIcons.heart, CupertinoIcons.heart_fill),
    datingChat: ToggleIcon(CupertinoIcons.bubble_left, CupertinoIcons.bubble_left_fill),
    // YoYo tabs
    yoyoNearby: ToggleIcon(CupertinoIcons.location, CupertinoIcons.location_fill),
    yoyoConnect: ToggleIcon(CupertinoIcons.link, CupertinoIcons.link_circle_fill),
    yoyoWave: ToggleIcon(CupertinoIcons.hand_raised, CupertinoIcons.hand_raised_fill),
    yoyoChat: ToggleIcon(CupertinoIcons.bubble_left, CupertinoIcons.bubble_left_fill),
    // Social tabs
    socialStumble: ToggleIcon(CupertinoIcons.shuffle, CupertinoIcons.shuffle_thick),
    socialFriends: ToggleIcon(CupertinoIcons.person_2, CupertinoIcons.person_2_fill),
    socialEvents: ToggleIcon(CupertinoIcons.calendar, CupertinoIcons.calendar_today),
    socialPost: ToggleIcon(CupertinoIcons.plus_square, CupertinoIcons.plus_square_fill),
    // Shop tabs — bag instead of Material's shopping_bag
    shopBrowse: ToggleIcon(CupertinoIcons.bag, CupertinoIcons.bag_fill),
    shopDeals: ToggleIcon(CupertinoIcons.tag, CupertinoIcons.tag_fill),
    shopSell: ToggleIcon(CupertinoIcons.cart, CupertinoIcons.cart_fill),
    shopMessages: ToggleIcon(CupertinoIcons.bubble_left, CupertinoIcons.bubble_left_fill),
    // Service FAB
    serviceVideo: ToggleIcon(CupertinoIcons.play_rectangle, CupertinoIcons.play_rectangle_fill),
    serviceDating: ToggleIcon(CupertinoIcons.heart, CupertinoIcons.heart_fill),
    serviceYoyo: ToggleIcon(CupertinoIcons.compass, CupertinoIcons.compass_fill),
    serviceSocial: ToggleIcon(CupertinoIcons.person_2, CupertinoIcons.person_2_fill),
    serviceShop: ToggleIcon(CupertinoIcons.bag, CupertinoIcons.bag_fill),
    // UI actions — Apple's distinctive icon language
    // iOS share icon: square with arrow up (NOT branching share)
    search: CupertinoIcons.search,
    close: CupertinoIcons.xmark,
    arrowBack: CupertinoIcons.chevron_back,
    chevronRight: CupertinoIcons.chevron_forward,
    check: CupertinoIcons.checkmark,
    checkCircle: CupertinoIcons.checkmark_circle_fill,
    moreHoriz: CupertinoIcons.ellipsis,
    share: CupertinoIcons.share,
    send: CupertinoIcons.paperplane,
    reply: CupertinoIcons.arrowshape_turn_up_left,
    favoriteOutline: CupertinoIcons.heart,
    favoriteFilled: CupertinoIcons.heart_fill,
    bookmarkOutline: CupertinoIcons.bookmark,
    bookmarkFilled: CupertinoIcons.bookmark_fill,
    visibilityOn: CupertinoIcons.eye,
    visibilityOff: CupertinoIcons.eye_slash,
    starFilled: CupertinoIcons.star_fill,
    chatBubbleOutline: CupertinoIcons.chat_bubble,
    chatOutline: CupertinoIcons.bubble_left,
    forum: CupertinoIcons.bubble_left_bubble_right,
    comment: CupertinoIcons.chat_bubble_text,
    edit: CupertinoIcons.pencil,
    editOutline: CupertinoIcons.pencil,
    settings: CupertinoIcons.gear,
    notifications: CupertinoIcons.bell_fill,
    notificationsOutline: CupertinoIcons.bell,
    personOutline: CupertinoIcons.person,
    personAdd: CupertinoIcons.person_badge_plus,
    personRemove: CupertinoIcons.person_badge_minus,
    storefront: CupertinoIcons.bag_fill,
    storefrontOutline: CupertinoIcons.bag,
    add: CupertinoIcons.plus,
    addCircle: CupertinoIcons.plus_circle,
    addPhoto: CupertinoIcons.camera,
    photoLibrary: CupertinoIcons.photo_on_rectangle,
    cameraAlt: CupertinoIcons.camera,
    cameraAltOutline: CupertinoIcons.camera,
    videocam: CupertinoIcons.videocam,
    flipCamera: CupertinoIcons.camera_rotate,
    timerOutline: CupertinoIcons.timer,
    timerFilled: CupertinoIcons.timer_fill,
    flashOn: CupertinoIcons.bolt_fill,
    flashOff: CupertinoIcons.bolt_slash,
    speedOutline: CupertinoIcons.slowmo,
    playArrow: CupertinoIcons.play,
    playCircleOutline: CupertinoIcons.play_circle,
    contentCut: CupertinoIcons.scissors,
    textFields: CupertinoIcons.textformat,
    emojiEmotions: CupertinoIcons.smiley,
    filterVintage: CupertinoIcons.wand_stars,
    tag: CupertinoIcons.tag,
    flag: CupertinoIcons.flag,
    lockOutline: CupertinoIcons.lock,
    blockOutline: CupertinoIcons.nosign,
    phoneOutline: CupertinoIcons.phone,
    emailOutline: CupertinoIcons.envelope,
    locationOff: CupertinoIcons.location_slash,
    tune: CupertinoIcons.slider_horizontal_3,
    filterList: CupertinoIcons.line_horizontal_3_decrease,
    refresh: CupertinoIcons.arrow_clockwise,
    radar: CupertinoIcons.antenna_radiowaves_left_right,
    localOffer: CupertinoIcons.tag_fill,
    localOfferOutline: CupertinoIcons.tag,
    shoppingBag: CupertinoIcons.bag_fill,
    gavel: CupertinoIcons.hammer,
    localFireDepartment: CupertinoIcons.flame_fill,
    campaign: CupertinoIcons.speaker_3_fill,
    locationOn: CupertinoIcons.location_fill,
    nearMe: CupertinoIcons.location_north_fill,
    group: CupertinoIcons.person_2_fill,
    groupOutline: CupertinoIcons.person_2,
    peopleOutline: CupertinoIcons.person_3,
    wavingHand: CupertinoIcons.hand_raised,
    image: CupertinoIcons.photo,
    verified: CupertinoIcons.checkmark_seal_fill,
    calendarToday: CupertinoIcons.calendar_today,
    linkIcon: CupertinoIcons.link,
    linkOutline: CupertinoIcons.link,
    replay: CupertinoIcons.arrow_counterclockwise,
    height: CupertinoIcons.arrow_up_down,
    schoolOutline: CupertinoIcons.book,
    localBarOutline: CupertinoIcons.music_note,
    workOutline: CupertinoIcons.briefcase,
    viewList: CupertinoIcons.list_bullet,
  );

  // ═══════════════════════════════════════════════════════════════════════
  //  Instagram Social — Closest Material match to Instagram's actual icons
  //  Key: share=send (paper airplane), comment=mode_comment, home=home,
  //       thin outlined strokes, filled on active, organic rounded shapes
  // ═══════════════════════════════════════════════════════════════════════

  static const instagramSocial = ProtoIconSet(
    name: 'Instagram Social',
    shortName: 'Insta',
    description: 'Paper airplane share, organic bubbles — closest to Instagram/Threads',
    // Video tabs — Instagram uses home/search/reels/shop/profile
    videoForYou: ToggleIcon(Icons.home_outlined, Icons.home_rounded),
    videoFollowing: ToggleIcon(Icons.people_outline_rounded, Icons.people_rounded),
    videoDiscover: ToggleIcon(Icons.explore_outlined, Icons.explore_rounded),
    videoCreate: ToggleIcon(Icons.add_box_outlined, Icons.add_box_rounded),
    // Dating tabs
    datingDiscover: ToggleIcon(Icons.explore_outlined, Icons.explore_rounded),
    datingMatches: ToggleIcon(Icons.favorite_border_rounded, Icons.favorite_rounded),
    datingLikes: ToggleIcon(Icons.favorite_border_rounded, Icons.favorite_rounded),
    datingChat: ToggleIcon(Icons.mode_comment_outlined, Icons.mode_comment_rounded),
    // YoYo tabs
    yoyoNearby: ToggleIcon(Icons.near_me_outlined, Icons.near_me_rounded),
    yoyoConnect: ToggleIcon(Icons.link_outlined, Icons.link_rounded),
    yoyoWave: ToggleIcon(Icons.waving_hand_outlined, Icons.waving_hand_rounded),
    yoyoChat: ToggleIcon(Icons.mode_comment_outlined, Icons.mode_comment_rounded),
    // Social tabs
    socialStumble: ToggleIcon(Icons.shuffle_outlined, Icons.shuffle_rounded),
    socialFriends: ToggleIcon(Icons.group_outlined, Icons.group_rounded),
    socialEvents: ToggleIcon(Icons.event_outlined, Icons.event_rounded),
    socialPost: ToggleIcon(Icons.add_box_outlined, Icons.add_box_rounded),
    // Shop tabs — Instagram uses outlined shopping bag
    shopBrowse: ToggleIcon(Icons.shopping_bag_outlined, Icons.shopping_bag_rounded),
    shopDeals: ToggleIcon(Icons.local_offer_outlined, Icons.local_offer_rounded),
    shopSell: ToggleIcon(Icons.sell_outlined, Icons.sell_rounded),
    shopMessages: ToggleIcon(Icons.mode_comment_outlined, Icons.mode_comment_rounded),
    // Service FAB
    serviceVideo: ToggleIcon(Icons.smart_display_outlined, Icons.smart_display_rounded),
    serviceDating: ToggleIcon(Icons.favorite_border_rounded, Icons.favorite_rounded),
    serviceYoyo: ToggleIcon(Icons.explore_outlined, Icons.explore_rounded),
    serviceSocial: ToggleIcon(Icons.people_outline_rounded, Icons.people_rounded),
    serviceShop: ToggleIcon(Icons.shopping_bag_outlined, Icons.shopping_bag_rounded),
    // UI actions — Instagram-matched choices
    search: Icons.search_rounded,
    close: Icons.close_rounded,
    arrowBack: Icons.arrow_back_ios_new_rounded,
    chevronRight: Icons.chevron_right_rounded,
    check: Icons.check_rounded,
    checkCircle: Icons.check_circle_rounded,
    moreHoriz: Icons.more_horiz_rounded,
    // KEY DIFFERENCE: Instagram uses paper airplane (send) for share, not branching share
    share: Icons.send_rounded,
    send: Icons.send_rounded,
    reply: Icons.reply_rounded,
    favoriteOutline: Icons.favorite_border_rounded,
    favoriteFilled: Icons.favorite_rounded,
    // Instagram bookmark is a clean flag/ribbon shape
    bookmarkOutline: Icons.bookmark_border_rounded,
    bookmarkFilled: Icons.bookmark_rounded,
    visibilityOn: Icons.visibility_rounded,
    visibilityOff: Icons.visibility_off_rounded,
    starFilled: Icons.star_rounded,
    // Instagram comment bubble is rounder — mode_comment is closer than chat_bubble
    chatBubbleOutline: Icons.mode_comment_outlined,
    chatOutline: Icons.mode_comment_outlined,
    forum: Icons.forum_rounded,
    comment: Icons.mode_comment_rounded,
    edit: Icons.edit_rounded,
    editOutline: Icons.edit_outlined,
    settings: Icons.settings_outlined,
    notifications: Icons.favorite_rounded,
    notificationsOutline: Icons.favorite_border_rounded,
    personOutline: Icons.person_outline_rounded,
    personAdd: Icons.person_add_rounded,
    personRemove: Icons.person_remove_rounded,
    storefront: Icons.shopping_bag_rounded,
    storefrontOutline: Icons.shopping_bag_outlined,
    // Instagram uses a boxed + for create, not circle
    add: Icons.add_rounded,
    addCircle: Icons.add_box_rounded,
    addPhoto: Icons.add_photo_alternate_rounded,
    photoLibrary: Icons.photo_library_rounded,
    cameraAlt: Icons.camera_alt_rounded,
    cameraAltOutline: Icons.camera_alt_outlined,
    videocam: Icons.smart_display_rounded,
    flipCamera: Icons.flip_camera_ios_outlined,
    timerOutline: Icons.timer_outlined,
    timerFilled: Icons.timer_rounded,
    flashOn: Icons.flash_on_rounded,
    flashOff: Icons.flash_off_rounded,
    speedOutline: Icons.speed_outlined,
    playArrow: Icons.play_arrow_rounded,
    playCircleOutline: Icons.smart_display_outlined,
    contentCut: Icons.content_cut_rounded,
    textFields: Icons.text_fields_rounded,
    emojiEmotions: Icons.emoji_emotions_rounded,
    filterVintage: Icons.filter_vintage_rounded,
    tag: Icons.tag_rounded,
    flag: Icons.flag_rounded,
    lockOutline: Icons.lock_outline_rounded,
    blockOutline: Icons.block_outlined,
    phoneOutline: Icons.phone_outlined,
    emailOutline: Icons.email_outlined,
    locationOff: Icons.location_off_outlined,
    tune: Icons.tune_outlined,
    filterList: Icons.filter_list_rounded,
    refresh: Icons.refresh_rounded,
    radar: Icons.radar_rounded,
    localOffer: Icons.local_offer_rounded,
    localOfferOutline: Icons.local_offer_outlined,
    shoppingBag: Icons.shopping_bag_rounded,
    gavel: Icons.gavel_rounded,
    localFireDepartment: Icons.local_fire_department_rounded,
    campaign: Icons.campaign_rounded,
    locationOn: Icons.location_on_rounded,
    nearMe: Icons.near_me_rounded,
    group: Icons.group_rounded,
    groupOutline: Icons.group_outlined,
    peopleOutline: Icons.people_outline_rounded,
    wavingHand: Icons.waving_hand_rounded,
    image: Icons.image_rounded,
    verified: Icons.verified_rounded,
    calendarToday: Icons.calendar_today_rounded,
    linkIcon: Icons.link_rounded,
    linkOutline: Icons.link_outlined,
    replay: Icons.replay_rounded,
    height: Icons.height_rounded,
    schoolOutline: Icons.school_outlined,
    localBarOutline: Icons.local_bar_outlined,
    workOutline: Icons.work_outline_rounded,
    viewList: Icons.view_list_rounded,
  );

  // ═══════════════════════════════════════════════════════════════════════
  //  1: Modern Outlined — Light, clean (generic outlined style)
  // ═══════════════════════════════════════════════════════════════════════

  static const modernOutlined = ProtoIconSet(
    name: 'Modern Outlined',
    shortName: 'Modern',
    description: 'Light stroke icons with rounded fills on selection',
    // Video tabs
    videoForYou: ToggleIcon(Icons.smart_display_outlined, Icons.smart_display_rounded),
    videoFollowing: ToggleIcon(Icons.people_outline_rounded, Icons.people_rounded),
    videoDiscover: ToggleIcon(Icons.explore_outlined, Icons.explore_rounded),
    videoCreate: ToggleIcon(Icons.add_circle_outline_rounded, Icons.add_circle_rounded),
    // Dating tabs
    datingDiscover: ToggleIcon(Icons.explore_outlined, Icons.explore_rounded),
    datingMatches: ToggleIcon(Icons.handshake_outlined, Icons.handshake_rounded),
    datingLikes: ToggleIcon(Icons.thumb_up_outlined, Icons.thumb_up_rounded),
    datingChat: ToggleIcon(Icons.chat_bubble_outline_rounded, Icons.chat_bubble_rounded),
    // YoYo tabs
    yoyoNearby: ToggleIcon(Icons.near_me_outlined, Icons.near_me_rounded),
    yoyoConnect: ToggleIcon(Icons.link_outlined, Icons.link_rounded),
    yoyoWave: ToggleIcon(Icons.waving_hand_outlined, Icons.waving_hand_rounded),
    yoyoChat: ToggleIcon(Icons.chat_outlined, Icons.chat_rounded),
    // Social tabs
    socialStumble: ToggleIcon(Icons.shuffle_outlined, Icons.shuffle_rounded),
    socialFriends: ToggleIcon(Icons.group_outlined, Icons.group_rounded),
    socialEvents: ToggleIcon(Icons.event_outlined, Icons.event_rounded),
    socialPost: ToggleIcon(Icons.create_outlined, Icons.create_rounded),
    // Shop tabs
    shopBrowse: ToggleIcon(Icons.shopping_bag_outlined, Icons.shopping_bag_rounded),
    shopDeals: ToggleIcon(Icons.local_offer_outlined, Icons.local_offer_rounded),
    shopSell: ToggleIcon(Icons.sell_outlined, Icons.sell_rounded),
    shopMessages: ToggleIcon(Icons.forum_outlined, Icons.forum_rounded),
    // Service FAB
    serviceVideo: ToggleIcon(Icons.play_circle_outline_rounded, Icons.play_circle_rounded),
    serviceDating: ToggleIcon(Icons.favorite_border_rounded, Icons.favorite_rounded),
    serviceYoyo: ToggleIcon(Icons.explore_outlined, Icons.explore_rounded),
    serviceSocial: ToggleIcon(Icons.people_outline_rounded, Icons.people_rounded),
    serviceShop: ToggleIcon(Icons.storefront_outlined, Icons.storefront_rounded),
    // UI actions
    search: Icons.search_outlined,
    close: Icons.close_rounded,
    arrowBack: Icons.arrow_back_ios_new_rounded,
    chevronRight: Icons.chevron_right_rounded,
    check: Icons.check_rounded,
    checkCircle: Icons.check_circle_rounded,
    moreHoriz: Icons.more_horiz_rounded,
    share: Icons.share_outlined,
    send: Icons.send_rounded,
    reply: Icons.reply_rounded,
    favoriteOutline: Icons.favorite_border_rounded,
    favoriteFilled: Icons.favorite_rounded,
    bookmarkOutline: Icons.bookmark_border_rounded,
    bookmarkFilled: Icons.bookmark_rounded,
    visibilityOn: Icons.visibility_rounded,
    visibilityOff: Icons.visibility_off_rounded,
    starFilled: Icons.star_rounded,
    chatBubbleOutline: Icons.chat_bubble_outline_rounded,
    chatOutline: Icons.chat_outlined,
    forum: Icons.forum_rounded,
    comment: Icons.comment_rounded,
    edit: Icons.edit_rounded,
    editOutline: Icons.edit_outlined,
    settings: Icons.settings_outlined,
    notifications: Icons.notifications_rounded,
    notificationsOutline: Icons.notifications_outlined,
    personOutline: Icons.person_outline_rounded,
    personAdd: Icons.person_add_rounded,
    personRemove: Icons.person_remove_rounded,
    storefront: Icons.storefront_rounded,
    storefrontOutline: Icons.storefront_outlined,
    add: Icons.add_rounded,
    addCircle: Icons.add_circle_rounded,
    addPhoto: Icons.add_photo_alternate_rounded,
    photoLibrary: Icons.photo_library_rounded,
    cameraAlt: Icons.camera_alt_rounded,
    cameraAltOutline: Icons.camera_alt_outlined,
    videocam: Icons.videocam_rounded,
    flipCamera: Icons.flip_camera_ios_outlined,
    timerOutline: Icons.timer_outlined,
    timerFilled: Icons.timer_rounded,
    flashOn: Icons.flash_on_rounded,
    flashOff: Icons.flash_off_rounded,
    speedOutline: Icons.speed_outlined,
    playArrow: Icons.play_arrow_rounded,
    playCircleOutline: Icons.play_circle_outline_rounded,
    contentCut: Icons.content_cut_rounded,
    textFields: Icons.text_fields_rounded,
    emojiEmotions: Icons.emoji_emotions_rounded,
    filterVintage: Icons.filter_vintage_rounded,
    tag: Icons.tag_rounded,
    flag: Icons.flag_rounded,
    lockOutline: Icons.lock_outline_rounded,
    blockOutline: Icons.block_outlined,
    phoneOutline: Icons.phone_outlined,
    emailOutline: Icons.email_outlined,
    locationOff: Icons.location_off_outlined,
    tune: Icons.tune_outlined,
    filterList: Icons.filter_list_rounded,
    refresh: Icons.refresh_rounded,
    radar: Icons.radar_rounded,
    localOffer: Icons.local_offer_rounded,
    localOfferOutline: Icons.local_offer_outlined,
    shoppingBag: Icons.shopping_bag_rounded,
    gavel: Icons.gavel_rounded,
    localFireDepartment: Icons.local_fire_department_rounded,
    campaign: Icons.campaign_rounded,
    locationOn: Icons.location_on_rounded,
    nearMe: Icons.near_me_rounded,
    group: Icons.group_rounded,
    groupOutline: Icons.group_outlined,
    peopleOutline: Icons.people_outline_rounded,
    wavingHand: Icons.waving_hand_rounded,
    image: Icons.image_rounded,
    verified: Icons.verified_rounded,
    calendarToday: Icons.calendar_today_rounded,
    linkIcon: Icons.link_rounded,
    linkOutline: Icons.link_outlined,
    replay: Icons.replay_rounded,
    height: Icons.height_rounded,
    schoolOutline: Icons.school_outlined,
    localBarOutline: Icons.local_bar_outlined,
    workOutline: Icons.work_outline_rounded,
    viewList: Icons.view_list_rounded,
  );

  // ═══════════════════════════════════════════════════════════════════════
  //  1: Rounded Classic — Warm, friendly (Google Material default)
  // ═══════════════════════════════════════════════════════════════════════

  static const roundedClassic = ProtoIconSet(
    name: 'Rounded Classic',
    shortName: 'Rounded',
    description: 'Soft rounded corners throughout for a warm, approachable feel',
    // Video tabs
    videoForYou: ToggleIcon(Icons.smart_display_outlined, Icons.smart_display_rounded),
    videoFollowing: ToggleIcon(Icons.people_outline_rounded, Icons.people_rounded),
    videoDiscover: ToggleIcon(Icons.explore_outlined, Icons.explore_rounded),
    videoCreate: ToggleIcon(Icons.add_circle_outline_rounded, Icons.add_circle_rounded),
    // Dating tabs
    datingDiscover: ToggleIcon(Icons.explore_outlined, Icons.explore_rounded),
    datingMatches: ToggleIcon(Icons.handshake_outlined, Icons.handshake_rounded),
    datingLikes: ToggleIcon(Icons.thumb_up_outlined, Icons.thumb_up_rounded),
    datingChat: ToggleIcon(Icons.chat_bubble_outline_rounded, Icons.chat_bubble_rounded),
    // YoYo tabs
    yoyoNearby: ToggleIcon(Icons.near_me_outlined, Icons.near_me_rounded),
    yoyoConnect: ToggleIcon(Icons.link_outlined, Icons.link_rounded),
    yoyoWave: ToggleIcon(Icons.waving_hand_outlined, Icons.waving_hand_rounded),
    yoyoChat: ToggleIcon(Icons.chat_outlined, Icons.chat_rounded),
    // Social tabs
    socialStumble: ToggleIcon(Icons.shuffle_outlined, Icons.shuffle_rounded),
    socialFriends: ToggleIcon(Icons.group_outlined, Icons.group_rounded),
    socialEvents: ToggleIcon(Icons.event_outlined, Icons.event_rounded),
    socialPost: ToggleIcon(Icons.create_outlined, Icons.create_rounded),
    // Shop tabs
    shopBrowse: ToggleIcon(Icons.shopping_bag_outlined, Icons.shopping_bag_rounded),
    shopDeals: ToggleIcon(Icons.local_offer_outlined, Icons.local_offer_rounded),
    shopSell: ToggleIcon(Icons.sell_outlined, Icons.sell_rounded),
    shopMessages: ToggleIcon(Icons.forum_outlined, Icons.forum_rounded),
    // Service FAB
    serviceVideo: ToggleIcon(Icons.play_circle_outline_rounded, Icons.play_circle_rounded),
    serviceDating: ToggleIcon(Icons.favorite_border_rounded, Icons.favorite_rounded),
    serviceYoyo: ToggleIcon(Icons.explore_outlined, Icons.explore_rounded),
    serviceSocial: ToggleIcon(Icons.people_outline_rounded, Icons.people_rounded),
    serviceShop: ToggleIcon(Icons.storefront_outlined, Icons.storefront_rounded),
    // UI actions — all _rounded
    search: Icons.search_rounded,
    close: Icons.close_rounded,
    arrowBack: Icons.arrow_back_ios_new_rounded,
    chevronRight: Icons.chevron_right_rounded,
    check: Icons.check_rounded,
    checkCircle: Icons.check_circle_rounded,
    moreHoriz: Icons.more_horiz_rounded,
    share: Icons.share_rounded,
    send: Icons.send_rounded,
    reply: Icons.reply_rounded,
    favoriteOutline: Icons.favorite_border_rounded,
    favoriteFilled: Icons.favorite_rounded,
    bookmarkOutline: Icons.bookmark_border_rounded,
    bookmarkFilled: Icons.bookmark_rounded,
    visibilityOn: Icons.visibility_rounded,
    visibilityOff: Icons.visibility_off_rounded,
    starFilled: Icons.star_rounded,
    chatBubbleOutline: Icons.chat_bubble_outline_rounded,
    chatOutline: Icons.chat_rounded,
    forum: Icons.forum_rounded,
    comment: Icons.comment_rounded,
    edit: Icons.edit_rounded,
    editOutline: Icons.edit_rounded,
    settings: Icons.settings_rounded,
    notifications: Icons.notifications_rounded,
    notificationsOutline: Icons.notifications_rounded,
    personOutline: Icons.person_rounded,
    personAdd: Icons.person_add_rounded,
    personRemove: Icons.person_remove_rounded,
    storefront: Icons.storefront_rounded,
    storefrontOutline: Icons.storefront_rounded,
    add: Icons.add_rounded,
    addCircle: Icons.add_circle_rounded,
    addPhoto: Icons.add_photo_alternate_rounded,
    photoLibrary: Icons.photo_library_rounded,
    cameraAlt: Icons.camera_alt_rounded,
    cameraAltOutline: Icons.camera_alt_rounded,
    videocam: Icons.videocam_rounded,
    flipCamera: Icons.flip_camera_ios_rounded,
    timerOutline: Icons.timer_rounded,
    timerFilled: Icons.timer_rounded,
    flashOn: Icons.flash_on_rounded,
    flashOff: Icons.flash_off_rounded,
    speedOutline: Icons.speed_rounded,
    playArrow: Icons.play_arrow_rounded,
    playCircleOutline: Icons.play_circle_rounded,
    contentCut: Icons.content_cut_rounded,
    textFields: Icons.text_fields_rounded,
    emojiEmotions: Icons.emoji_emotions_rounded,
    filterVintage: Icons.filter_vintage_rounded,
    tag: Icons.tag_rounded,
    flag: Icons.flag_rounded,
    lockOutline: Icons.lock_rounded,
    blockOutline: Icons.block_rounded,
    phoneOutline: Icons.phone_rounded,
    emailOutline: Icons.email_rounded,
    locationOff: Icons.location_off_rounded,
    tune: Icons.tune_rounded,
    filterList: Icons.filter_list_rounded,
    refresh: Icons.refresh_rounded,
    radar: Icons.radar_rounded,
    localOffer: Icons.local_offer_rounded,
    localOfferOutline: Icons.local_offer_rounded,
    shoppingBag: Icons.shopping_bag_rounded,
    gavel: Icons.gavel_rounded,
    localFireDepartment: Icons.local_fire_department_rounded,
    campaign: Icons.campaign_rounded,
    locationOn: Icons.location_on_rounded,
    nearMe: Icons.near_me_rounded,
    group: Icons.group_rounded,
    groupOutline: Icons.group_rounded,
    peopleOutline: Icons.people_rounded,
    wavingHand: Icons.waving_hand_rounded,
    image: Icons.image_rounded,
    verified: Icons.verified_rounded,
    calendarToday: Icons.calendar_today_rounded,
    linkIcon: Icons.link_rounded,
    linkOutline: Icons.link_rounded,
    replay: Icons.replay_rounded,
    height: Icons.height_rounded,
    schoolOutline: Icons.school_rounded,
    localBarOutline: Icons.local_bar_rounded,
    workOutline: Icons.work_rounded,
    viewList: Icons.view_list_rounded,
  );

  // ═══════════════════════════════════════════════════════════════════════
  //  2: Sharp Geometric — Precise, technical (editorial aesthetic)
  // ═══════════════════════════════════════════════════════════════════════

  static const sharpGeometric = ProtoIconSet(
    name: 'Sharp Geometric',
    shortName: 'Sharp',
    description: 'Crisp angular icons with no corner rounding',
    // Video tabs
    videoForYou: ToggleIcon(Icons.smart_display_outlined, Icons.smart_display_sharp),
    videoFollowing: ToggleIcon(Icons.people_outline_sharp, Icons.people_sharp),
    videoDiscover: ToggleIcon(Icons.explore_outlined, Icons.explore_sharp),
    videoCreate: ToggleIcon(Icons.add_circle_outline_sharp, Icons.add_circle_sharp),
    // Dating tabs
    datingDiscover: ToggleIcon(Icons.explore_outlined, Icons.explore_sharp),
    datingMatches: ToggleIcon(Icons.handshake_outlined, Icons.handshake_sharp),
    datingLikes: ToggleIcon(Icons.thumb_up_outlined, Icons.thumb_up_sharp),
    datingChat: ToggleIcon(Icons.chat_bubble_outline_sharp, Icons.chat_bubble_sharp),
    // YoYo tabs
    yoyoNearby: ToggleIcon(Icons.near_me_outlined, Icons.near_me_sharp),
    yoyoConnect: ToggleIcon(Icons.link_outlined, Icons.link_sharp),
    yoyoWave: ToggleIcon(Icons.waving_hand_outlined, Icons.waving_hand_sharp),
    yoyoChat: ToggleIcon(Icons.chat_outlined, Icons.chat_sharp),
    // Social tabs
    socialStumble: ToggleIcon(Icons.shuffle_outlined, Icons.shuffle_sharp),
    socialFriends: ToggleIcon(Icons.group_outlined, Icons.group_sharp),
    socialEvents: ToggleIcon(Icons.event_outlined, Icons.event_sharp),
    socialPost: ToggleIcon(Icons.create_outlined, Icons.create_sharp),
    // Shop tabs
    shopBrowse: ToggleIcon(Icons.shopping_bag_outlined, Icons.shopping_bag_sharp),
    shopDeals: ToggleIcon(Icons.local_offer_outlined, Icons.local_offer_sharp),
    shopSell: ToggleIcon(Icons.sell_outlined, Icons.sell_sharp),
    shopMessages: ToggleIcon(Icons.forum_outlined, Icons.forum_sharp),
    // Service FAB
    serviceVideo: ToggleIcon(Icons.play_circle_outline_sharp, Icons.play_circle_sharp),
    serviceDating: ToggleIcon(Icons.favorite_border_sharp, Icons.favorite_sharp),
    serviceYoyo: ToggleIcon(Icons.explore_outlined, Icons.explore_sharp),
    serviceSocial: ToggleIcon(Icons.people_outline_sharp, Icons.people_sharp),
    serviceShop: ToggleIcon(Icons.storefront_outlined, Icons.storefront_sharp),
    // UI actions — all _sharp (falling back to base where _sharp unavailable)
    search: Icons.search_sharp,
    close: Icons.close_sharp,
    arrowBack: Icons.arrow_back_ios_new_sharp,
    chevronRight: Icons.chevron_right_sharp,
    check: Icons.check_sharp,
    checkCircle: Icons.check_circle_sharp,
    moreHoriz: Icons.more_horiz_sharp,
    share: Icons.share_sharp,
    send: Icons.send_sharp,
    reply: Icons.reply_sharp,
    favoriteOutline: Icons.favorite_border_sharp,
    favoriteFilled: Icons.favorite_sharp,
    bookmarkOutline: Icons.bookmark_border_sharp,
    bookmarkFilled: Icons.bookmark_sharp,
    visibilityOn: Icons.visibility_sharp,
    visibilityOff: Icons.visibility_off_sharp,
    starFilled: Icons.star_sharp,
    chatBubbleOutline: Icons.chat_bubble_outline_sharp,
    chatOutline: Icons.chat_sharp,
    forum: Icons.forum_sharp,
    comment: Icons.comment_sharp,
    edit: Icons.edit_sharp,
    editOutline: Icons.edit_sharp,
    settings: Icons.settings_sharp,
    notifications: Icons.notifications_sharp,
    notificationsOutline: Icons.notifications_sharp,
    personOutline: Icons.person_outline_sharp,
    personAdd: Icons.person_add_sharp,
    personRemove: Icons.person_remove_sharp,
    storefront: Icons.storefront_sharp,
    storefrontOutline: Icons.storefront_sharp,
    add: Icons.add_sharp,
    addCircle: Icons.add_circle_sharp,
    addPhoto: Icons.add_photo_alternate_sharp,
    photoLibrary: Icons.photo_library_sharp,
    cameraAlt: Icons.camera_alt_sharp,
    cameraAltOutline: Icons.camera_alt_sharp,
    videocam: Icons.videocam_sharp,
    flipCamera: Icons.flip_camera_ios_sharp,
    timerOutline: Icons.timer_sharp,
    timerFilled: Icons.timer_sharp,
    flashOn: Icons.flash_on_sharp,
    flashOff: Icons.flash_off_sharp,
    speedOutline: Icons.speed_sharp,
    playArrow: Icons.play_arrow_sharp,
    playCircleOutline: Icons.play_circle_outline_sharp,
    contentCut: Icons.content_cut_sharp,
    textFields: Icons.text_fields_sharp,
    emojiEmotions: Icons.emoji_emotions_sharp,
    filterVintage: Icons.filter_vintage_sharp,
    tag: Icons.tag_sharp,
    flag: Icons.flag_sharp,
    lockOutline: Icons.lock_sharp,
    blockOutline: Icons.block_sharp,
    phoneOutline: Icons.phone_sharp,
    emailOutline: Icons.email_sharp,
    locationOff: Icons.location_off_sharp,
    tune: Icons.tune_sharp,
    filterList: Icons.filter_list_sharp,
    refresh: Icons.refresh_sharp,
    radar: Icons.radar_sharp,
    localOffer: Icons.local_offer_sharp,
    localOfferOutline: Icons.local_offer_sharp,
    shoppingBag: Icons.shopping_bag_sharp,
    gavel: Icons.gavel_sharp,
    localFireDepartment: Icons.local_fire_department_sharp,
    campaign: Icons.campaign_sharp,
    locationOn: Icons.location_on_sharp,
    nearMe: Icons.near_me_sharp,
    group: Icons.group_sharp,
    groupOutline: Icons.group_sharp,
    peopleOutline: Icons.people_sharp,
    wavingHand: Icons.waving_hand_sharp,
    image: Icons.image_sharp,
    verified: Icons.verified_sharp,
    calendarToday: Icons.calendar_today_sharp,
    linkIcon: Icons.link_sharp,
    linkOutline: Icons.link_sharp,
    replay: Icons.replay_sharp,
    height: Icons.height_sharp,
    schoolOutline: Icons.school_sharp,
    localBarOutline: Icons.local_bar_sharp,
    workOutline: Icons.work_sharp,
    viewList: Icons.view_list_sharp,
  );

  // ═══════════════════════════════════════════════════════════════════════
  //  3: Standard Filled — Bold, high-contrast (classic Material)
  // ═══════════════════════════════════════════════════════════════════════

  static const standardFilled = ProtoIconSet(
    name: 'Standard Filled',
    shortName: 'Filled',
    description: 'Bold filled icons for maximum weight and presence',
    // Video tabs — outlined inactive, filled active
    videoForYou: ToggleIcon(Icons.smart_display_outlined, Icons.smart_display),
    videoFollowing: ToggleIcon(Icons.people_outlined, Icons.people),
    videoDiscover: ToggleIcon(Icons.explore_outlined, Icons.explore),
    videoCreate: ToggleIcon(Icons.add_circle_outlined, Icons.add_circle),
    // Dating tabs
    datingDiscover: ToggleIcon(Icons.explore_outlined, Icons.explore),
    datingMatches: ToggleIcon(Icons.handshake_outlined, Icons.handshake),
    datingLikes: ToggleIcon(Icons.thumb_up_outlined, Icons.thumb_up),
    datingChat: ToggleIcon(Icons.chat_bubble_outline, Icons.chat_bubble),
    // YoYo tabs
    yoyoNearby: ToggleIcon(Icons.near_me_outlined, Icons.near_me),
    yoyoConnect: ToggleIcon(Icons.link_outlined, Icons.link),
    yoyoWave: ToggleIcon(Icons.waving_hand_outlined, Icons.waving_hand),
    yoyoChat: ToggleIcon(Icons.chat_outlined, Icons.chat),
    // Social tabs
    socialStumble: ToggleIcon(Icons.shuffle_outlined, Icons.shuffle),
    socialFriends: ToggleIcon(Icons.group_outlined, Icons.group),
    socialEvents: ToggleIcon(Icons.event_outlined, Icons.event),
    socialPost: ToggleIcon(Icons.create_outlined, Icons.create),
    // Shop tabs
    shopBrowse: ToggleIcon(Icons.shopping_bag_outlined, Icons.shopping_bag),
    shopDeals: ToggleIcon(Icons.local_offer_outlined, Icons.local_offer),
    shopSell: ToggleIcon(Icons.sell_outlined, Icons.sell),
    shopMessages: ToggleIcon(Icons.forum_outlined, Icons.forum),
    // Service FAB
    serviceVideo: ToggleIcon(Icons.play_circle_outlined, Icons.play_circle),
    serviceDating: ToggleIcon(Icons.favorite_outline, Icons.favorite),
    serviceYoyo: ToggleIcon(Icons.explore_outlined, Icons.explore),
    serviceSocial: ToggleIcon(Icons.people_outlined, Icons.people),
    serviceShop: ToggleIcon(Icons.storefront_outlined, Icons.storefront),
    // UI actions — all default (filled, no suffix)
    search: Icons.search,
    close: Icons.close,
    arrowBack: Icons.arrow_back_ios_new,
    chevronRight: Icons.chevron_right,
    check: Icons.check,
    checkCircle: Icons.check_circle,
    moreHoriz: Icons.more_horiz,
    share: Icons.share,
    send: Icons.send,
    reply: Icons.reply,
    favoriteOutline: Icons.favorite_border,
    favoriteFilled: Icons.favorite,
    bookmarkOutline: Icons.bookmark_border,
    bookmarkFilled: Icons.bookmark,
    visibilityOn: Icons.visibility,
    visibilityOff: Icons.visibility_off,
    starFilled: Icons.star,
    chatBubbleOutline: Icons.chat_bubble_outline,
    chatOutline: Icons.chat,
    forum: Icons.forum,
    comment: Icons.comment,
    edit: Icons.edit,
    editOutline: Icons.edit,
    settings: Icons.settings,
    notifications: Icons.notifications,
    notificationsOutline: Icons.notifications,
    personOutline: Icons.person_outline,
    personAdd: Icons.person_add,
    personRemove: Icons.person_remove,
    storefront: Icons.storefront,
    storefrontOutline: Icons.storefront,
    add: Icons.add,
    addCircle: Icons.add_circle,
    addPhoto: Icons.add_photo_alternate,
    photoLibrary: Icons.photo_library,
    cameraAlt: Icons.camera_alt,
    cameraAltOutline: Icons.camera_alt,
    videocam: Icons.videocam,
    flipCamera: Icons.flip_camera_ios,
    timerOutline: Icons.timer,
    timerFilled: Icons.timer,
    flashOn: Icons.flash_on,
    flashOff: Icons.flash_off,
    speedOutline: Icons.speed,
    playArrow: Icons.play_arrow,
    playCircleOutline: Icons.play_circle_outline,
    contentCut: Icons.content_cut,
    textFields: Icons.text_fields,
    emojiEmotions: Icons.emoji_emotions,
    filterVintage: Icons.filter_vintage,
    tag: Icons.tag,
    flag: Icons.flag,
    lockOutline: Icons.lock,
    blockOutline: Icons.block,
    phoneOutline: Icons.phone,
    emailOutline: Icons.email,
    locationOff: Icons.location_off,
    tune: Icons.tune,
    filterList: Icons.filter_list,
    refresh: Icons.refresh,
    radar: Icons.radar,
    localOffer: Icons.local_offer,
    localOfferOutline: Icons.local_offer,
    shoppingBag: Icons.shopping_bag,
    gavel: Icons.gavel,
    localFireDepartment: Icons.local_fire_department,
    campaign: Icons.campaign,
    locationOn: Icons.location_on,
    nearMe: Icons.near_me,
    group: Icons.group,
    groupOutline: Icons.group,
    peopleOutline: Icons.people,
    wavingHand: Icons.waving_hand,
    image: Icons.image,
    verified: Icons.verified,
    calendarToday: Icons.calendar_today,
    linkIcon: Icons.link,
    linkOutline: Icons.link,
    replay: Icons.replay,
    height: Icons.height,
    schoolOutline: Icons.school,
    localBarOutline: Icons.local_bar,
    workOutline: Icons.work,
    viewList: Icons.view_list,
  );

  // ═══════════════════════════════════════════════════════════════════════
  //  4: Conceptual Remix — Alternative metaphors for each icon concept
  // ═══════════════════════════════════════════════════════════════════════

  static const conceptualRemix = ProtoIconSet(
    name: 'Conceptual Remix',
    shortName: 'Remix',
    description: 'Alternative icon metaphors — star for love, globe for discover',
    // Video tabs — film/movie metaphor instead of play button
    videoForYou: ToggleIcon(Icons.movie_outlined, Icons.movie_rounded),
    videoFollowing: ToggleIcon(Icons.person_pin_outlined, Icons.person_pin_rounded),
    videoDiscover: ToggleIcon(Icons.travel_explore, Icons.travel_explore),
    videoCreate: ToggleIcon(Icons.library_add_outlined, Icons.library_add_rounded),
    // Dating tabs — globe/star metaphor
    datingDiscover: ToggleIcon(Icons.public_outlined, Icons.public_rounded),
    datingMatches: ToggleIcon(Icons.group_work_outlined, Icons.group_work_rounded),
    datingLikes: ToggleIcon(Icons.star_border_rounded, Icons.star_rounded),
    datingChat: ToggleIcon(Icons.question_answer_outlined, Icons.question_answer_rounded),
    // YoYo tabs — crosshair/swap metaphor
    yoyoNearby: ToggleIcon(Icons.my_location_outlined, Icons.my_location_rounded),
    yoyoConnect: ToggleIcon(Icons.swap_horiz_outlined, Icons.swap_horiz_rounded),
    yoyoWave: ToggleIcon(Icons.pan_tool_outlined, Icons.pan_tool_rounded),
    yoyoChat: ToggleIcon(Icons.sms_outlined, Icons.sms_rounded),
    // Social tabs — autorenew/ticket metaphor
    socialStumble: ToggleIcon(Icons.autorenew_outlined, Icons.autorenew_rounded),
    socialFriends: ToggleIcon(Icons.group_work_outlined, Icons.group_work_rounded),
    socialEvents: ToggleIcon(Icons.local_activity_outlined, Icons.local_activity_rounded),
    socialPost: ToggleIcon(Icons.note_add_outlined, Icons.note_add_rounded),
    // Shop tabs — mall/loyalty metaphor
    shopBrowse: ToggleIcon(Icons.local_mall_outlined, Icons.local_mall_rounded),
    shopDeals: ToggleIcon(Icons.loyalty_outlined, Icons.loyalty_rounded),
    shopSell: ToggleIcon(Icons.monetization_on_outlined, Icons.monetization_on_rounded),
    shopMessages: ToggleIcon(Icons.question_answer_outlined, Icons.question_answer_rounded),
    // Service FAB
    serviceVideo: ToggleIcon(Icons.movie_outlined, Icons.movie_rounded),
    serviceDating: ToggleIcon(Icons.star_border_rounded, Icons.star_rounded),
    serviceYoyo: ToggleIcon(Icons.public_outlined, Icons.public_rounded),
    serviceSocial: ToggleIcon(Icons.group_work_outlined, Icons.group_work_rounded),
    serviceShop: ToggleIcon(Icons.local_mall_outlined, Icons.local_mall_rounded),
    // UI actions — alternative metaphors throughout
    search: Icons.travel_explore,
    close: Icons.cancel_rounded,
    arrowBack: Icons.keyboard_arrow_left_rounded,
    chevronRight: Icons.keyboard_arrow_right_rounded,
    check: Icons.done_all_rounded,
    checkCircle: Icons.verified_rounded,
    moreHoriz: Icons.more_vert_rounded,
    share: Icons.ios_share_rounded,
    send: Icons.publish_rounded,
    reply: Icons.keyboard_return_rounded,
    favoriteOutline: Icons.star_border_rounded,
    favoriteFilled: Icons.star_rounded,
    bookmarkOutline: Icons.turned_in_not_rounded,
    bookmarkFilled: Icons.turned_in_rounded,
    visibilityOn: Icons.remove_red_eye_rounded,
    visibilityOff: Icons.visibility_off_rounded,
    starFilled: Icons.thumb_up_rounded,
    chatBubbleOutline: Icons.question_answer_outlined,
    chatOutline: Icons.sms_outlined,
    forum: Icons.question_answer_rounded,
    comment: Icons.rate_review_rounded,
    edit: Icons.brush_rounded,
    editOutline: Icons.brush_outlined,
    settings: Icons.build_rounded,
    notifications: Icons.notifications_active_rounded,
    notificationsOutline: Icons.notifications_active_outlined,
    personOutline: Icons.account_circle_outlined,
    personAdd: Icons.person_add_alt_1_rounded,
    personRemove: Icons.person_remove_rounded,
    storefront: Icons.local_mall_rounded,
    storefrontOutline: Icons.local_mall_outlined,
    add: Icons.library_add_rounded,
    addCircle: Icons.add_box_rounded,
    addPhoto: Icons.add_a_photo_rounded,
    photoLibrary: Icons.collections_rounded,
    cameraAlt: Icons.photo_camera_rounded,
    cameraAltOutline: Icons.photo_camera_outlined,
    videocam: Icons.movie_rounded,
    flipCamera: Icons.flip_camera_ios_rounded,
    timerOutline: Icons.hourglass_empty_rounded,
    timerFilled: Icons.hourglass_full_rounded,
    flashOn: Icons.flash_on_rounded,
    flashOff: Icons.flash_off_rounded,
    speedOutline: Icons.slow_motion_video_rounded,
    playArrow: Icons.play_circle_rounded,
    playCircleOutline: Icons.play_circle_outline_rounded,
    contentCut: Icons.content_cut_rounded,
    textFields: Icons.title_rounded,
    emojiEmotions: Icons.mood_rounded,
    filterVintage: Icons.auto_awesome_rounded,
    tag: Icons.label_rounded,
    flag: Icons.outlined_flag_rounded,
    lockOutline: Icons.lock_open_rounded,
    blockOutline: Icons.do_not_disturb_rounded,
    phoneOutline: Icons.call_rounded,
    emailOutline: Icons.alternate_email_rounded,
    locationOff: Icons.location_off_rounded,
    tune: Icons.equalizer_rounded,
    filterList: Icons.sort_rounded,
    refresh: Icons.sync_rounded,
    radar: Icons.track_changes_rounded,
    localOffer: Icons.loyalty_rounded,
    localOfferOutline: Icons.loyalty_outlined,
    shoppingBag: Icons.local_mall_rounded,
    gavel: Icons.gavel_rounded,
    localFireDepartment: Icons.whatshot_rounded,
    campaign: Icons.campaign_rounded,
    locationOn: Icons.my_location_rounded,
    nearMe: Icons.gps_fixed_rounded,
    group: Icons.group_work_rounded,
    groupOutline: Icons.group_work_outlined,
    peopleOutline: Icons.supervisor_account_outlined,
    wavingHand: Icons.pan_tool_rounded,
    image: Icons.photo_rounded,
    verified: Icons.verified_rounded,
    calendarToday: Icons.date_range_rounded,
    linkIcon: Icons.insert_link_rounded,
    linkOutline: Icons.link_off_rounded,
    replay: Icons.replay_rounded,
    height: Icons.straighten_rounded,
    schoolOutline: Icons.school_outlined,
    localBarOutline: Icons.local_bar_outlined,
    workOutline: Icons.business_center_outlined,
    viewList: Icons.list_alt_rounded,
  );

  // ═══════════════════════════════════════════════════════════════════════
  //  5: Minimal Glyph — Simplest possible icon for each concept
  // ═══════════════════════════════════════════════════════════════════════

  static const minimalGlyph = ProtoIconSet(
    name: 'Minimal Glyph',
    shortName: 'Minimal',
    description: 'Reduced to essentials — simplest glyph for each function',
    // Video tabs — TV/face metaphor
    videoForYou: ToggleIcon(Icons.live_tv_outlined, Icons.live_tv),
    videoFollowing: ToggleIcon(Icons.supervisor_account_outlined, Icons.supervisor_account),
    videoDiscover: ToggleIcon(Icons.language_outlined, Icons.language),
    videoCreate: ToggleIcon(Icons.playlist_add_outlined, Icons.playlist_add),
    // Dating tabs
    datingDiscover: ToggleIcon(Icons.face_outlined, Icons.face),
    datingMatches: ToggleIcon(Icons.import_export_outlined, Icons.import_export),
    datingLikes: ToggleIcon(Icons.grade_outlined, Icons.grade),
    datingChat: ToggleIcon(Icons.sms_outlined, Icons.sms),
    // YoYo tabs
    yoyoNearby: ToggleIcon(Icons.pin_drop_outlined, Icons.pin_drop),
    yoyoConnect: ToggleIcon(Icons.device_hub_outlined, Icons.device_hub),
    yoyoWave: ToggleIcon(Icons.touch_app_outlined, Icons.touch_app),
    yoyoChat: ToggleIcon(Icons.textsms_outlined, Icons.textsms),
    // Social tabs
    socialStumble: ToggleIcon(Icons.explore_outlined, Icons.explore),
    socialFriends: ToggleIcon(Icons.supervisor_account_outlined, Icons.supervisor_account),
    socialEvents: ToggleIcon(Icons.event_available_outlined, Icons.event_available),
    socialPost: ToggleIcon(Icons.note_add_outlined, Icons.note_add),
    // Shop tabs
    shopBrowse: ToggleIcon(Icons.store_outlined, Icons.store),
    shopDeals: ToggleIcon(Icons.sell_outlined, Icons.sell),
    shopSell: ToggleIcon(Icons.add_shopping_cart_outlined, Icons.add_shopping_cart),
    shopMessages: ToggleIcon(Icons.email_outlined, Icons.email),
    // Service FAB
    serviceVideo: ToggleIcon(Icons.live_tv_outlined, Icons.live_tv),
    serviceDating: ToggleIcon(Icons.grade_outlined, Icons.grade),
    serviceYoyo: ToggleIcon(Icons.language_outlined, Icons.language),
    serviceSocial: ToggleIcon(Icons.supervisor_account_outlined, Icons.supervisor_account),
    serviceShop: ToggleIcon(Icons.store_outlined, Icons.store),
    // UI actions — minimal choices
    search: Icons.manage_search,
    close: Icons.remove_circle_outline,
    arrowBack: Icons.keyboard_arrow_left,
    chevronRight: Icons.keyboard_arrow_right,
    check: Icons.done_outlined,
    checkCircle: Icons.check_circle_outline,
    moreHoriz: Icons.menu,
    share: Icons.launch,
    send: Icons.call_made,
    reply: Icons.call_received,
    favoriteOutline: Icons.grade_outlined,
    favoriteFilled: Icons.grade,
    bookmarkOutline: Icons.label_outline,
    bookmarkFilled: Icons.label,
    visibilityOn: Icons.remove_red_eye_outlined,
    visibilityOff: Icons.visibility_off_outlined,
    starFilled: Icons.emoji_events,
    chatBubbleOutline: Icons.sms_outlined,
    chatOutline: Icons.textsms_outlined,
    forum: Icons.question_answer,
    comment: Icons.rate_review_outlined,
    edit: Icons.create_outlined,
    editOutline: Icons.create_outlined,
    settings: Icons.more_vert,
    notifications: Icons.campaign_outlined,
    notificationsOutline: Icons.campaign_outlined,
    personOutline: Icons.face_outlined,
    personAdd: Icons.person_add_outlined,
    personRemove: Icons.person_remove_outlined,
    storefront: Icons.store,
    storefrontOutline: Icons.store_outlined,
    add: Icons.playlist_add,
    addCircle: Icons.add_box_outlined,
    addPhoto: Icons.add_a_photo_outlined,
    photoLibrary: Icons.collections_outlined,
    cameraAlt: Icons.center_focus_strong_outlined,
    cameraAltOutline: Icons.center_focus_strong_outlined,
    videocam: Icons.live_tv_outlined,
    flipCamera: Icons.flip_camera_ios_outlined,
    timerOutline: Icons.hourglass_empty,
    timerFilled: Icons.hourglass_full,
    flashOn: Icons.flash_on_outlined,
    flashOff: Icons.flash_off_outlined,
    speedOutline: Icons.speed_outlined,
    playArrow: Icons.play_arrow_outlined,
    playCircleOutline: Icons.play_circle_outline,
    contentCut: Icons.content_cut_outlined,
    textFields: Icons.text_fields_outlined,
    emojiEmotions: Icons.sentiment_satisfied_outlined,
    filterVintage: Icons.filter_vintage_outlined,
    tag: Icons.label_outline,
    flag: Icons.outlined_flag,
    lockOutline: Icons.lock_open_outlined,
    blockOutline: Icons.do_not_disturb_outlined,
    phoneOutline: Icons.call_outlined,
    emailOutline: Icons.mail_outline,
    locationOff: Icons.location_off_outlined,
    tune: Icons.straighten_outlined,
    filterList: Icons.sort_outlined,
    refresh: Icons.autorenew_outlined,
    radar: Icons.track_changes_outlined,
    localOffer: Icons.sell_outlined,
    localOfferOutline: Icons.sell_outlined,
    shoppingBag: Icons.store_outlined,
    gavel: Icons.gavel_outlined,
    localFireDepartment: Icons.whatshot_outlined,
    campaign: Icons.campaign_outlined,
    locationOn: Icons.pin_drop,
    nearMe: Icons.gps_fixed,
    group: Icons.supervisor_account,
    groupOutline: Icons.supervisor_account_outlined,
    peopleOutline: Icons.people_alt_outlined,
    wavingHand: Icons.touch_app,
    image: Icons.photo_outlined,
    verified: Icons.verified_outlined,
    calendarToday: Icons.event_available_outlined,
    linkIcon: Icons.insert_link,
    linkOutline: Icons.link_off,
    replay: Icons.replay,
    height: Icons.straighten,
    schoolOutline: Icons.school_outlined,
    localBarOutline: Icons.local_bar_outlined,
    workOutline: Icons.business_center_outlined,
    viewList: Icons.reorder,
  );

  // ═══════════════════════════════════════════════════════════════════════
  //  6: Expressive Social — Bold, human-centric, gesture-oriented
  // ═══════════════════════════════════════════════════════════════════════

  static const expressiveSocial = ProtoIconSet(
    name: 'Expressive Social',
    shortName: 'Express',
    description: 'Human-centric icons emphasising gesture and emotion',
    // Video tabs — screen/people metaphor
    videoForYou: ToggleIcon(Icons.ondemand_video_outlined, Icons.ondemand_video),
    videoFollowing: ToggleIcon(Icons.recent_actors_outlined, Icons.recent_actors),
    videoDiscover: ToggleIcon(Icons.saved_search_outlined, Icons.saved_search),
    videoCreate: ToggleIcon(Icons.post_add_outlined, Icons.post_add),
    // Dating tabs — person/heart metaphor
    datingDiscover: ToggleIcon(Icons.person_search_outlined, Icons.person_search),
    datingMatches: ToggleIcon(Icons.connect_without_contact_outlined, Icons.connect_without_contact),
    datingLikes: ToggleIcon(Icons.thumb_up_outlined, Icons.thumb_up),
    datingChat: ToggleIcon(Icons.textsms_outlined, Icons.textsms),
    // YoYo tabs — navigation/gesture metaphor
    yoyoNearby: ToggleIcon(Icons.navigation_outlined, Icons.navigation),
    yoyoConnect: ToggleIcon(Icons.group_add_outlined, Icons.group_add),
    yoyoWave: ToggleIcon(Icons.waving_hand_outlined, Icons.waving_hand),
    yoyoChat: ToggleIcon(Icons.mark_chat_unread_outlined, Icons.mark_chat_unread),
    // Social tabs
    socialStumble: ToggleIcon(Icons.person_search_outlined, Icons.person_search),
    socialFriends: ToggleIcon(Icons.connect_without_contact_outlined, Icons.connect_without_contact),
    socialEvents: ToggleIcon(Icons.celebration_outlined, Icons.celebration),
    socialPost: ToggleIcon(Icons.post_add_outlined, Icons.post_add),
    // Shop tabs — cart/gift metaphor
    shopBrowse: ToggleIcon(Icons.shopping_cart_outlined, Icons.shopping_cart),
    shopDeals: ToggleIcon(Icons.redeem_outlined, Icons.redeem),
    shopSell: ToggleIcon(Icons.volunteer_activism_outlined, Icons.volunteer_activism),
    shopMessages: ToggleIcon(Icons.mark_chat_unread_outlined, Icons.mark_chat_unread),
    // Service FAB
    serviceVideo: ToggleIcon(Icons.ondemand_video_outlined, Icons.ondemand_video),
    serviceDating: ToggleIcon(Icons.thumb_up_outlined, Icons.thumb_up),
    serviceYoyo: ToggleIcon(Icons.navigation_outlined, Icons.navigation),
    serviceSocial: ToggleIcon(Icons.connect_without_contact_outlined, Icons.connect_without_contact),
    serviceShop: ToggleIcon(Icons.shopping_cart_outlined, Icons.shopping_cart),
    // UI actions — expressive, human-centric
    search: Icons.saved_search,
    close: Icons.highlight_off,
    arrowBack: Icons.arrow_back,
    chevronRight: Icons.arrow_forward_ios,
    check: Icons.playlist_add_check,
    checkCircle: Icons.task_alt,
    moreHoriz: Icons.drag_indicator,
    share: Icons.ios_share,
    send: Icons.forward_to_inbox,
    reply: Icons.quickreply,
    favoriteOutline: Icons.thumb_up_outlined,
    favoriteFilled: Icons.thumb_up,
    bookmarkOutline: Icons.push_pin_outlined,
    bookmarkFilled: Icons.push_pin,
    visibilityOn: Icons.visibility,
    visibilityOff: Icons.visibility_off,
    starFilled: Icons.whatshot,
    chatBubbleOutline: Icons.textsms_outlined,
    chatOutline: Icons.mark_chat_unread_outlined,
    forum: Icons.question_answer,
    comment: Icons.rate_review,
    edit: Icons.color_lens,
    editOutline: Icons.color_lens_outlined,
    settings: Icons.construction,
    notifications: Icons.notification_important,
    notificationsOutline: Icons.notification_important_outlined,
    personOutline: Icons.person_search_outlined,
    personAdd: Icons.group_add,
    personRemove: Icons.person_off,
    storefront: Icons.shopping_cart,
    storefrontOutline: Icons.shopping_cart_outlined,
    add: Icons.post_add,
    addCircle: Icons.add_circle,
    addPhoto: Icons.add_a_photo,
    photoLibrary: Icons.collections,
    cameraAlt: Icons.linked_camera,
    cameraAltOutline: Icons.linked_camera,
    videocam: Icons.ondemand_video,
    flipCamera: Icons.flip_camera_ios,
    timerOutline: Icons.timer_outlined,
    timerFilled: Icons.timer,
    flashOn: Icons.flash_on,
    flashOff: Icons.flash_off,
    speedOutline: Icons.speed,
    playArrow: Icons.play_arrow,
    playCircleOutline: Icons.play_circle_outline,
    contentCut: Icons.content_cut,
    textFields: Icons.text_fields,
    emojiEmotions: Icons.emoji_emotions,
    filterVintage: Icons.auto_awesome,
    tag: Icons.sell,
    flag: Icons.report,
    lockOutline: Icons.lock_outline,
    blockOutline: Icons.person_off_outlined,
    phoneOutline: Icons.phone_callback,
    emailOutline: Icons.forward_to_inbox,
    locationOff: Icons.location_off,
    tune: Icons.graphic_eq,
    filterList: Icons.filter_list,
    refresh: Icons.autorenew,
    radar: Icons.radar,
    localOffer: Icons.redeem,
    localOfferOutline: Icons.redeem_outlined,
    shoppingBag: Icons.shopping_cart,
    gavel: Icons.gavel,
    localFireDepartment: Icons.whatshot,
    campaign: Icons.campaign,
    locationOn: Icons.navigation,
    nearMe: Icons.near_me,
    group: Icons.connect_without_contact,
    groupOutline: Icons.connect_without_contact,
    peopleOutline: Icons.people,
    wavingHand: Icons.waving_hand,
    image: Icons.image,
    verified: Icons.verified,
    calendarToday: Icons.event,
    linkIcon: Icons.link,
    linkOutline: Icons.link_off,
    replay: Icons.replay,
    height: Icons.height,
    schoolOutline: Icons.school,
    localBarOutline: Icons.local_bar,
    workOutline: Icons.work,
    viewList: Icons.view_list,
  );

  // ═══════════════════════════════════════════════════════════════════════
  //  7: Technical Blueprint — Engineering/data-oriented icons
  // ═══════════════════════════════════════════════════════════════════════

  static const technicalBlueprint = ProtoIconSet(
    name: 'Technical Blueprint',
    shortName: 'Tech',
    description: 'Engineering-inspired icons with data and precision metaphors',
    // Video tabs — technical/data metaphor
    videoForYou: ToggleIcon(Icons.slideshow_outlined, Icons.slideshow),
    videoFollowing: ToggleIcon(Icons.people_alt_outlined, Icons.people_alt),
    videoDiscover: ToggleIcon(Icons.find_in_page_outlined, Icons.find_in_page),
    videoCreate: ToggleIcon(Icons.add_to_queue_outlined, Icons.add_to_queue),
    // Dating tabs
    datingDiscover: ToggleIcon(Icons.person_search_outlined, Icons.person_search),
    datingMatches: ToggleIcon(Icons.compare_arrows_outlined, Icons.compare_arrows),
    datingLikes: ToggleIcon(Icons.loyalty_outlined, Icons.loyalty),
    datingChat: ToggleIcon(Icons.email_outlined, Icons.email),
    // YoYo tabs
    yoyoNearby: ToggleIcon(Icons.gps_not_fixed, Icons.gps_fixed),
    yoyoConnect: ToggleIcon(Icons.device_hub_outlined, Icons.device_hub),
    yoyoWave: ToggleIcon(Icons.notifications_active_outlined, Icons.notifications_active),
    yoyoChat: ToggleIcon(Icons.email_outlined, Icons.email),
    // Social tabs
    socialStumble: ToggleIcon(Icons.find_in_page_outlined, Icons.find_in_page),
    socialFriends: ToggleIcon(Icons.people_alt_outlined, Icons.people_alt),
    socialEvents: ToggleIcon(Icons.calendar_today_outlined, Icons.calendar_today),
    socialPost: ToggleIcon(Icons.post_add_outlined, Icons.post_add),
    // Shop tabs
    shopBrowse: ToggleIcon(Icons.inventory_2_outlined, Icons.inventory_2),
    shopDeals: ToggleIcon(Icons.price_check_outlined, Icons.price_check),
    shopSell: ToggleIcon(Icons.point_of_sale_outlined, Icons.point_of_sale),
    shopMessages: ToggleIcon(Icons.email_outlined, Icons.email),
    // Service FAB
    serviceVideo: ToggleIcon(Icons.slideshow_outlined, Icons.slideshow),
    serviceDating: ToggleIcon(Icons.loyalty_outlined, Icons.loyalty),
    serviceYoyo: ToggleIcon(Icons.gps_not_fixed, Icons.gps_fixed),
    serviceSocial: ToggleIcon(Icons.people_alt_outlined, Icons.people_alt),
    serviceShop: ToggleIcon(Icons.inventory_2_outlined, Icons.inventory_2),
    // UI actions — technical/engineering metaphors
    search: Icons.find_in_page_sharp,
    close: Icons.cancel_sharp,
    arrowBack: Icons.first_page_sharp,
    chevronRight: Icons.last_page_sharp,
    check: Icons.check_box_sharp,
    checkCircle: Icons.verified_sharp,
    moreHoriz: Icons.reorder_sharp,
    share: Icons.reply_all_sharp,
    send: Icons.upload_sharp,
    reply: Icons.reply_sharp,
    favoriteOutline: Icons.loyalty_outlined,
    favoriteFilled: Icons.loyalty,
    bookmarkOutline: Icons.label_outline,
    bookmarkFilled: Icons.label,
    visibilityOn: Icons.visibility_sharp,
    visibilityOff: Icons.visibility_off_sharp,
    starFilled: Icons.military_tech,
    chatBubbleOutline: Icons.email_outlined,
    chatOutline: Icons.email_sharp,
    forum: Icons.email,
    comment: Icons.rate_review_sharp,
    edit: Icons.architecture,
    editOutline: Icons.architecture_outlined,
    settings: Icons.settings_applications_sharp,
    notifications: Icons.priority_high_sharp,
    notificationsOutline: Icons.priority_high_outlined,
    personOutline: Icons.badge_outlined,
    personAdd: Icons.person_add_sharp,
    personRemove: Icons.person_remove_sharp,
    storefront: Icons.inventory_2,
    storefrontOutline: Icons.inventory_2_outlined,
    add: Icons.add_to_queue,
    addCircle: Icons.add_box_sharp,
    addPhoto: Icons.add_a_photo_sharp,
    photoLibrary: Icons.photo_library_sharp,
    cameraAlt: Icons.panorama_fish_eye,
    cameraAltOutline: Icons.panorama_fish_eye_outlined,
    videocam: Icons.slideshow_sharp,
    flipCamera: Icons.flip_camera_ios_sharp,
    timerOutline: Icons.timer_sharp,
    timerFilled: Icons.timer_sharp,
    flashOn: Icons.flash_on_sharp,
    flashOff: Icons.flash_off_sharp,
    speedOutline: Icons.speed_sharp,
    playArrow: Icons.play_arrow_sharp,
    playCircleOutline: Icons.play_circle_outline_sharp,
    contentCut: Icons.content_cut_sharp,
    textFields: Icons.text_fields_sharp,
    emojiEmotions: Icons.emoji_emotions_sharp,
    filterVintage: Icons.filter_vintage_sharp,
    tag: Icons.label_sharp,
    flag: Icons.report_sharp,
    lockOutline: Icons.lock_sharp,
    blockOutline: Icons.block_sharp,
    phoneOutline: Icons.phone_sharp,
    emailOutline: Icons.email_sharp,
    locationOff: Icons.location_off_sharp,
    tune: Icons.graphic_eq_sharp,
    filterList: Icons.filter_list_sharp,
    refresh: Icons.sync_sharp,
    radar: Icons.track_changes_sharp,
    localOffer: Icons.price_check,
    localOfferOutline: Icons.price_check,
    shoppingBag: Icons.inventory_2_sharp,
    gavel: Icons.gavel_sharp,
    localFireDepartment: Icons.whatshot_sharp,
    campaign: Icons.priority_high_sharp,
    locationOn: Icons.gps_fixed,
    nearMe: Icons.gps_not_fixed,
    group: Icons.people_alt,
    groupOutline: Icons.people_alt_outlined,
    peopleOutline: Icons.people_alt_outlined,
    wavingHand: Icons.notifications_active,
    image: Icons.image_sharp,
    verified: Icons.verified_sharp,
    calendarToday: Icons.calendar_today_sharp,
    linkIcon: Icons.link_sharp,
    linkOutline: Icons.link_off_sharp,
    replay: Icons.replay_sharp,
    height: Icons.straighten_sharp,
    schoolOutline: Icons.school_sharp,
    localBarOutline: Icons.local_bar_sharp,
    workOutline: Icons.work_sharp,
    viewList: Icons.table_rows_sharp,
  );

  // ═══════════════════════════════════════════════════════════════════════
  //  10: Phosphor Duotone — 6-weight icon system with balanced geometry
  //  Key: regular/fill toggle, camelCase names, distinct from Material
  // ═══════════════════════════════════════════════════════════════════════

  static const phosphorDuotone = ProtoIconSet(
    name: 'Phosphor Duotone',
    shortName: 'Phosphor',
    description: 'Balanced geometry with regular/fill toggle — 6 weights available',
    // Video tabs
    videoForYou: ToggleIcon(PhosphorIconsRegular.house, PhosphorIconsFill.house),
    videoFollowing: ToggleIcon(PhosphorIconsRegular.users, PhosphorIconsFill.users),
    videoDiscover: ToggleIcon(PhosphorIconsRegular.compass, PhosphorIconsFill.compass),
    videoCreate: ToggleIcon(PhosphorIconsRegular.plusCircle, PhosphorIconsFill.plusCircle),
    // Dating tabs
    datingDiscover: ToggleIcon(PhosphorIconsRegular.compass, PhosphorIconsFill.compass),
    datingMatches: ToggleIcon(PhosphorIconsRegular.usersThree, PhosphorIconsFill.usersThree),
    datingLikes: ToggleIcon(PhosphorIconsRegular.heart, PhosphorIconsFill.heart),
    datingChat: ToggleIcon(PhosphorIconsRegular.chatCircle, PhosphorIconsFill.chatCircle),
    // YoYo tabs
    yoyoNearby: ToggleIcon(PhosphorIconsRegular.mapPin, PhosphorIconsFill.mapPin),
    yoyoConnect: ToggleIcon(PhosphorIconsRegular.link, PhosphorIconsFill.link),
    yoyoWave: ToggleIcon(PhosphorIconsRegular.handWaving, PhosphorIconsFill.handWaving),
    yoyoChat: ToggleIcon(PhosphorIconsRegular.chatCircle, PhosphorIconsFill.chatCircle),
    // Social tabs
    socialStumble: ToggleIcon(PhosphorIconsRegular.shuffle, PhosphorIconsFill.shuffle),
    socialFriends: ToggleIcon(PhosphorIconsRegular.users, PhosphorIconsFill.users),
    socialEvents: ToggleIcon(PhosphorIconsRegular.calendar, PhosphorIconsFill.calendar),
    socialPost: ToggleIcon(PhosphorIconsRegular.plusCircle, PhosphorIconsFill.plusCircle),
    // Shop tabs
    shopBrowse: ToggleIcon(PhosphorIconsRegular.shoppingBag, PhosphorIconsFill.shoppingBag),
    shopDeals: ToggleIcon(PhosphorIconsRegular.tag, PhosphorIconsFill.tag),
    shopSell: ToggleIcon(PhosphorIconsRegular.shoppingCart, PhosphorIconsFill.shoppingCart),
    shopMessages: ToggleIcon(PhosphorIconsRegular.chatDots, PhosphorIconsFill.chatDots),
    // Service FAB
    serviceVideo: ToggleIcon(PhosphorIconsRegular.playCircle, PhosphorIconsFill.playCircle),
    serviceDating: ToggleIcon(PhosphorIconsRegular.heart, PhosphorIconsFill.heart),
    serviceYoyo: ToggleIcon(PhosphorIconsRegular.compass, PhosphorIconsFill.compass),
    serviceSocial: ToggleIcon(PhosphorIconsRegular.users, PhosphorIconsFill.users),
    serviceShop: ToggleIcon(PhosphorIconsRegular.storefront, PhosphorIconsFill.storefront),
    // UI actions
    search: PhosphorIconsRegular.magnifyingGlass,
    close: PhosphorIconsRegular.xCircle,
    arrowBack: PhosphorIconsRegular.arrowLeft,
    chevronRight: PhosphorIconsRegular.caretRight,
    check: PhosphorIconsRegular.check,
    checkCircle: PhosphorIconsFill.checkCircle,
    moreHoriz: PhosphorIconsRegular.dotsThree,
    share: PhosphorIconsRegular.shareNetwork,
    send: PhosphorIconsRegular.paperPlaneRight,
    reply: PhosphorIconsRegular.arrowBendUpLeft,
    favoriteOutline: PhosphorIconsRegular.heart,
    favoriteFilled: PhosphorIconsFill.heart,
    bookmarkOutline: PhosphorIconsRegular.bookmark,
    bookmarkFilled: PhosphorIconsFill.bookmark,
    visibilityOn: PhosphorIconsRegular.eye,
    visibilityOff: PhosphorIconsRegular.eyeSlash,
    starFilled: PhosphorIconsFill.star,
    chatBubbleOutline: PhosphorIconsRegular.chatCircle,
    chatOutline: PhosphorIconsRegular.chat,
    forum: PhosphorIconsRegular.chatsCircle,
    comment: PhosphorIconsFill.chatCircle,
    edit: PhosphorIconsRegular.pencil,
    editOutline: PhosphorIconsRegular.pencil,
    settings: PhosphorIconsRegular.gear,
    notifications: PhosphorIconsFill.bell,
    notificationsOutline: PhosphorIconsRegular.bell,
    personOutline: PhosphorIconsRegular.user,
    personAdd: PhosphorIconsRegular.userPlus,
    personRemove: PhosphorIconsRegular.userMinus,
    storefront: PhosphorIconsFill.storefront,
    storefrontOutline: PhosphorIconsRegular.storefront,
    add: PhosphorIconsRegular.plus,
    addCircle: PhosphorIconsRegular.plusCircle,
    addPhoto: PhosphorIconsRegular.camera,
    photoLibrary: PhosphorIconsRegular.image,
    cameraAlt: PhosphorIconsRegular.camera,
    cameraAltOutline: PhosphorIconsRegular.camera,
    videocam: PhosphorIconsRegular.videoCamera,
    flipCamera: PhosphorIconsRegular.cameraRotate,
    timerOutline: PhosphorIconsRegular.timer,
    timerFilled: PhosphorIconsFill.timer,
    flashOn: PhosphorIconsRegular.lightning,
    flashOff: PhosphorIconsRegular.lightningSlash,
    speedOutline: PhosphorIconsRegular.speedometer,
    playArrow: PhosphorIconsRegular.play,
    playCircleOutline: PhosphorIconsRegular.playCircle,
    contentCut: PhosphorIconsRegular.scissors,
    textFields: PhosphorIconsRegular.textT,
    emojiEmotions: PhosphorIconsRegular.smiley,
    filterVintage: PhosphorIconsRegular.sparkle,
    tag: PhosphorIconsRegular.tag,
    flag: PhosphorIconsRegular.flag,
    lockOutline: PhosphorIconsRegular.lock,
    blockOutline: PhosphorIconsRegular.prohibit,
    phoneOutline: PhosphorIconsRegular.phone,
    emailOutline: PhosphorIconsRegular.envelope,
    locationOff: PhosphorIconsRegular.mapPinLine,
    tune: PhosphorIconsRegular.sliders,
    filterList: PhosphorIconsRegular.funnel,
    refresh: PhosphorIconsRegular.arrowCounterClockwise,
    radar: PhosphorIconsRegular.broadcast,
    localOffer: PhosphorIconsFill.tag,
    localOfferOutline: PhosphorIconsRegular.tag,
    shoppingBag: PhosphorIconsFill.shoppingBag,
    gavel: PhosphorIconsRegular.gavel,
    localFireDepartment: PhosphorIconsRegular.fire,
    campaign: PhosphorIconsRegular.megaphone,
    locationOn: PhosphorIconsFill.mapPin,
    nearMe: PhosphorIconsRegular.navigationArrow,
    group: PhosphorIconsFill.users,
    groupOutline: PhosphorIconsRegular.users,
    peopleOutline: PhosphorIconsRegular.usersThree,
    wavingHand: PhosphorIconsRegular.handWaving,
    image: PhosphorIconsRegular.image,
    verified: PhosphorIconsFill.sealCheck,
    calendarToday: PhosphorIconsRegular.calendarBlank,
    linkIcon: PhosphorIconsRegular.link,
    linkOutline: PhosphorIconsRegular.linkBreak,
    replay: PhosphorIconsRegular.repeat,
    height: PhosphorIconsRegular.arrowsDownUp,
    schoolOutline: PhosphorIconsRegular.graduationCap,
    localBarOutline: PhosphorIconsRegular.wine,
    workOutline: PhosphorIconsRegular.briefcase,
    viewList: PhosphorIconsRegular.listBullets,
  );

  // ═══════════════════════════════════════════════════════════════════════
  //  11: Lucide Clean — Thin 2px stroke, minimal & modern, single weight
  //  Key: outline-only (no fill variant), kebab→camelCase naming
  // ═══════════════════════════════════════════════════════════════════════

  static const lucideClean = ProtoIconSet(
    name: 'Lucide Clean',
    shortName: 'Lucide',
    description: 'Thin 2px strokes, minimal modern aesthetic — single weight',
    // Video tabs — Lucide: single-weight outline only, no fill variants available.
    // All ToggleIcons use same icon both states (color-only toggle).
    videoForYou: ToggleIcon(LucideIcons.house, LucideIcons.house), // Lucide: no fill variant
    videoFollowing: ToggleIcon(LucideIcons.users, LucideIcons.users),
    videoDiscover: ToggleIcon(LucideIcons.compass, LucideIcons.compass),
    videoCreate: ToggleIcon(LucideIcons.circlePlus, LucideIcons.circlePlus),
    // Dating tabs
    datingDiscover: ToggleIcon(LucideIcons.compass, LucideIcons.compass),
    datingMatches: ToggleIcon(LucideIcons.users, LucideIcons.users),
    datingLikes: ToggleIcon(LucideIcons.heart, LucideIcons.heart),
    datingChat: ToggleIcon(LucideIcons.messageCircle, LucideIcons.messageCircle),
    // YoYo tabs
    yoyoNearby: ToggleIcon(LucideIcons.mapPin, LucideIcons.mapPin),
    yoyoConnect: ToggleIcon(LucideIcons.link, LucideIcons.link),
    yoyoWave: ToggleIcon(LucideIcons.hand, LucideIcons.hand),
    yoyoChat: ToggleIcon(LucideIcons.messageCircle, LucideIcons.messageCircle),
    // Social tabs
    socialStumble: ToggleIcon(LucideIcons.shuffle, LucideIcons.shuffle),
    socialFriends: ToggleIcon(LucideIcons.users, LucideIcons.users),
    socialEvents: ToggleIcon(LucideIcons.calendar, LucideIcons.calendar),
    socialPost: ToggleIcon(LucideIcons.circlePlus, LucideIcons.circlePlus),
    // Shop tabs
    shopBrowse: ToggleIcon(LucideIcons.shoppingBag, LucideIcons.shoppingBag),
    shopDeals: ToggleIcon(LucideIcons.tag, LucideIcons.tag),
    shopSell: ToggleIcon(LucideIcons.shoppingCart, LucideIcons.shoppingCart),
    shopMessages: ToggleIcon(LucideIcons.messageSquare, LucideIcons.messageSquare),
    // Service FAB
    serviceVideo: ToggleIcon(LucideIcons.circlePlay, LucideIcons.circlePlay),
    serviceDating: ToggleIcon(LucideIcons.heart, LucideIcons.heart),
    serviceYoyo: ToggleIcon(LucideIcons.compass, LucideIcons.compass),
    serviceSocial: ToggleIcon(LucideIcons.users, LucideIcons.users),
    serviceShop: ToggleIcon(LucideIcons.store, LucideIcons.store),
    // UI actions
    search: LucideIcons.search,
    close: LucideIcons.x,
    arrowBack: LucideIcons.arrowLeft,
    chevronRight: LucideIcons.chevronRight,
    check: LucideIcons.check,
    checkCircle: LucideIcons.circleCheck,
    moreHoriz: LucideIcons.move,
    share: LucideIcons.share2,
    send: LucideIcons.send,
    reply: LucideIcons.reply,
    favoriteOutline: LucideIcons.heart,
    favoriteFilled: LucideIcons.heart,
    bookmarkOutline: LucideIcons.bookmark,
    bookmarkFilled: LucideIcons.bookmark,
    visibilityOn: LucideIcons.eye,
    visibilityOff: LucideIcons.eyeOff,
    starFilled: LucideIcons.star,
    chatBubbleOutline: LucideIcons.messageCircle,
    chatOutline: LucideIcons.messageSquare,
    forum: LucideIcons.messageCircle,
    comment: LucideIcons.messageSquare,
    edit: LucideIcons.pencil,
    editOutline: LucideIcons.pencilLine,
    settings: LucideIcons.settings,
    notifications: LucideIcons.bell,
    notificationsOutline: LucideIcons.bell,
    personOutline: LucideIcons.user,
    personAdd: LucideIcons.userPlus,
    personRemove: LucideIcons.userMinus,
    storefront: LucideIcons.store,
    storefrontOutline: LucideIcons.store,
    add: LucideIcons.plus,
    addCircle: LucideIcons.circlePlus,
    addPhoto: LucideIcons.camera,
    photoLibrary: LucideIcons.image,
    cameraAlt: LucideIcons.camera,
    cameraAltOutline: LucideIcons.camera,
    videocam: LucideIcons.video,
    flipCamera: LucideIcons.camera,
    timerOutline: LucideIcons.clock,
    timerFilled: LucideIcons.clock,
    flashOn: LucideIcons.zap,
    flashOff: LucideIcons.zapOff,
    speedOutline: LucideIcons.gauge,
    playArrow: LucideIcons.play,
    playCircleOutline: LucideIcons.circlePlay,
    contentCut: LucideIcons.scissors,
    textFields: LucideIcons.type,
    emojiEmotions: LucideIcons.smile,
    filterVintage: LucideIcons.sparkles,
    tag: LucideIcons.tag,
    flag: LucideIcons.flag,
    lockOutline: LucideIcons.lock,
    blockOutline: LucideIcons.circleX,
    phoneOutline: LucideIcons.phone,
    emailOutline: LucideIcons.mail,
    locationOff: LucideIcons.mapPinOff,
    tune: LucideIcons.slidersHorizontal,
    filterList: LucideIcons.listFilter,
    refresh: LucideIcons.refreshCw,
    radar: LucideIcons.circleDot,
    localOffer: LucideIcons.tag,
    localOfferOutline: LucideIcons.tag,
    shoppingBag: LucideIcons.shoppingBag,
    gavel: LucideIcons.gavel,
    localFireDepartment: LucideIcons.flame,
    campaign: LucideIcons.megaphone,
    locationOn: LucideIcons.mapPin,
    nearMe: LucideIcons.compass,
    group: LucideIcons.users,
    groupOutline: LucideIcons.users,
    peopleOutline: LucideIcons.users,
    wavingHand: LucideIcons.hand,
    image: LucideIcons.image,
    verified: LucideIcons.badgeCheck,
    calendarToday: LucideIcons.calendar,
    linkIcon: LucideIcons.link,
    linkOutline: LucideIcons.link2Off,
    replay: LucideIcons.repeat,
    height: LucideIcons.arrowUpDown,
    schoolOutline: LucideIcons.graduationCap,
    localBarOutline: LucideIcons.wine,
    workOutline: LucideIcons.briefcase,
    viewList: LucideIcons.list,
  );

  // ═══════════════════════════════════════════════════════════════════════
  //  12: Heroicons Geometric — Tailwind ecosystem, clean geometry
  //  Key: outline/solid toggle, Tailwind CSS companion icons
  // ═══════════════════════════════════════════════════════════════════════

  static const heroiconsGeo = ProtoIconSet(
    name: 'Heroicons Geometric',
    shortName: 'Hero',
    description: 'Tailwind ecosystem icons — clean geometric outline/solid toggle',
    // Video tabs
    videoForYou: ToggleIcon(HeroiconsOutline.home, HeroiconsSolid.home),
    videoFollowing: ToggleIcon(HeroiconsOutline.users, HeroiconsSolid.users),
    videoDiscover: ToggleIcon(HeroiconsOutline.globeAlt, HeroiconsSolid.globeAlt),
    videoCreate: ToggleIcon(HeroiconsOutline.plusCircle, HeroiconsSolid.plusCircle),
    // Dating tabs
    datingDiscover: ToggleIcon(HeroiconsOutline.globeAlt, HeroiconsSolid.globeAlt),
    datingMatches: ToggleIcon(HeroiconsOutline.userGroup, HeroiconsSolid.userGroup),
    datingLikes: ToggleIcon(HeroiconsOutline.heart, HeroiconsSolid.heart),
    datingChat: ToggleIcon(HeroiconsOutline.chatBubbleLeft, HeroiconsSolid.chatBubbleLeft),
    // YoYo tabs
    yoyoNearby: ToggleIcon(HeroiconsOutline.mapPin, HeroiconsSolid.mapPin),
    yoyoConnect: ToggleIcon(HeroiconsOutline.link, HeroiconsSolid.link),
    yoyoWave: ToggleIcon(HeroiconsOutline.handRaised, HeroiconsSolid.handRaised),
    yoyoChat: ToggleIcon(HeroiconsOutline.chatBubbleLeft, HeroiconsSolid.chatBubbleLeft),
    // Social tabs
    socialStumble: ToggleIcon(HeroiconsOutline.arrowsRightLeft, HeroiconsSolid.arrowsRightLeft),
    socialFriends: ToggleIcon(HeroiconsOutline.userGroup, HeroiconsSolid.userGroup),
    socialEvents: ToggleIcon(HeroiconsOutline.calendar, HeroiconsSolid.calendar),
    socialPost: ToggleIcon(HeroiconsOutline.plusCircle, HeroiconsSolid.plusCircle),
    // Shop tabs
    shopBrowse: ToggleIcon(HeroiconsOutline.shoppingBag, HeroiconsSolid.shoppingBag),
    shopDeals: ToggleIcon(HeroiconsOutline.tag, HeroiconsSolid.tag),
    shopSell: ToggleIcon(HeroiconsOutline.shoppingCart, HeroiconsSolid.shoppingCart),
    shopMessages: ToggleIcon(HeroiconsOutline.chatBubbleLeftRight, HeroiconsSolid.chatBubbleLeftRight),
    // Service FAB
    serviceVideo: ToggleIcon(HeroiconsOutline.playCircle, HeroiconsSolid.playCircle),
    serviceDating: ToggleIcon(HeroiconsOutline.heart, HeroiconsSolid.heart),
    serviceYoyo: ToggleIcon(HeroiconsOutline.globeAlt, HeroiconsSolid.globeAlt),
    serviceSocial: ToggleIcon(HeroiconsOutline.userGroup, HeroiconsSolid.userGroup),
    serviceShop: ToggleIcon(HeroiconsOutline.buildingStorefront, HeroiconsSolid.buildingStorefront),
    // UI actions
    search: HeroiconsOutline.magnifyingGlass,
    close: HeroiconsOutline.xMark,
    arrowBack: HeroiconsOutline.arrowLeft,
    chevronRight: HeroiconsOutline.chevronRight,
    check: HeroiconsOutline.check,
    checkCircle: HeroiconsSolid.checkCircle,
    moreHoriz: HeroiconsOutline.ellipsisHorizontal,
    share: HeroiconsOutline.share,
    send: HeroiconsOutline.paperAirplane,
    reply: HeroiconsOutline.arrowUturnLeft,
    favoriteOutline: HeroiconsOutline.heart,
    favoriteFilled: HeroiconsSolid.heart,
    bookmarkOutline: HeroiconsOutline.bookmark,
    bookmarkFilled: HeroiconsSolid.bookmark,
    visibilityOn: HeroiconsOutline.eye,
    visibilityOff: HeroiconsOutline.eyeSlash,
    starFilled: HeroiconsSolid.star,
    chatBubbleOutline: HeroiconsOutline.chatBubbleOvalLeft,
    chatOutline: HeroiconsOutline.chatBubbleLeft,
    forum: HeroiconsOutline.chatBubbleLeftRight,
    comment: HeroiconsSolid.chatBubbleBottomCenter,
    edit: HeroiconsOutline.pencil,
    editOutline: HeroiconsOutline.pencilSquare,
    settings: HeroiconsOutline.cog6Tooth,
    notifications: HeroiconsSolid.bell,
    notificationsOutline: HeroiconsOutline.bell,
    personOutline: HeroiconsOutline.user,
    personAdd: HeroiconsOutline.userPlus,
    personRemove: HeroiconsOutline.userMinus,
    storefront: HeroiconsSolid.buildingStorefront,
    storefrontOutline: HeroiconsOutline.buildingStorefront,
    add: HeroiconsOutline.plus,
    addCircle: HeroiconsOutline.plusCircle,
    addPhoto: HeroiconsOutline.camera,
    photoLibrary: HeroiconsOutline.photo,
    cameraAlt: HeroiconsOutline.camera,
    cameraAltOutline: HeroiconsOutline.camera,
    videocam: HeroiconsOutline.videoCamera,
    flipCamera: HeroiconsOutline.camera,
    timerOutline: HeroiconsOutline.clock,
    timerFilled: HeroiconsSolid.clock,
    flashOn: HeroiconsOutline.bolt,
    flashOff: HeroiconsOutline.boltSlash,
    speedOutline: HeroiconsOutline.forward,
    playArrow: HeroiconsOutline.play,
    playCircleOutline: HeroiconsOutline.playCircle,
    contentCut: HeroiconsOutline.scissors,
    textFields: HeroiconsOutline.bars3BottomLeft,
    emojiEmotions: HeroiconsOutline.faceSmile,
    filterVintage: HeroiconsOutline.sparkles,
    tag: HeroiconsOutline.tag,
    flag: HeroiconsOutline.flag,
    lockOutline: HeroiconsOutline.lockClosed,
    blockOutline: HeroiconsOutline.noSymbol,
    phoneOutline: HeroiconsOutline.phone,
    emailOutline: HeroiconsOutline.envelope,
    locationOff: HeroiconsOutline.mapPin,
    tune: HeroiconsOutline.adjustmentsHorizontal,
    filterList: HeroiconsOutline.funnel,
    refresh: HeroiconsOutline.arrowPath,
    radar: HeroiconsOutline.signal,
    localOffer: HeroiconsSolid.tag,
    localOfferOutline: HeroiconsOutline.tag,
    shoppingBag: HeroiconsSolid.shoppingBag,
    gavel: HeroiconsOutline.scale,
    localFireDepartment: HeroiconsOutline.fire,
    campaign: HeroiconsOutline.megaphone,
    locationOn: HeroiconsSolid.mapPin,
    nearMe: HeroiconsOutline.mapPin,
    group: HeroiconsSolid.userGroup,
    groupOutline: HeroiconsOutline.userGroup,
    peopleOutline: HeroiconsOutline.users,
    wavingHand: HeroiconsOutline.handRaised,
    image: HeroiconsOutline.photo,
    verified: HeroiconsSolid.checkBadge,
    calendarToday: HeroiconsOutline.calendarDays,
    linkIcon: HeroiconsOutline.link,
    linkOutline: HeroiconsOutline.linkSlash,
    replay: HeroiconsOutline.arrowPath,
    height: HeroiconsOutline.arrowsUpDown,
    schoolOutline: HeroiconsOutline.academicCap,
    localBarOutline: HeroiconsOutline.beaker,
    workOutline: HeroiconsOutline.briefcase,
    viewList: HeroiconsOutline.bars3,
  );

  // ═══════════════════════════════════════════════════════════════════════
  //  13: Iconsax Bold — Vuesax-inspired, 1,000+ icons, outline/bold toggle
  //  Key: name=outline, name_copy=bold variant, snake_case naming
  // ═══════════════════════════════════════════════════════════════════════

  static const iconsaxBold = ProtoIconSet(
    name: 'Iconsax Bold',
    shortName: 'Iconsax',
    description: 'Vuesax-inspired design system — outline to bold toggle',
    // Video tabs
    videoForYou: ToggleIcon(Iconsax.home, Iconsax.home_copy),
    videoFollowing: ToggleIcon(Iconsax.people, Iconsax.people_copy),
    videoDiscover: ToggleIcon(Iconsax.global, Iconsax.global_copy),
    videoCreate: ToggleIcon(Iconsax.add_circle, Iconsax.add_circle_copy),
    // Dating tabs
    datingDiscover: ToggleIcon(Iconsax.global, Iconsax.global_copy),
    datingMatches: ToggleIcon(Iconsax.people, Iconsax.people_copy),
    datingLikes: ToggleIcon(Iconsax.heart, Iconsax.heart_copy),
    datingChat: ToggleIcon(Iconsax.message, Iconsax.message_copy),
    // YoYo tabs
    yoyoNearby: ToggleIcon(Iconsax.location, Iconsax.location_copy),
    yoyoConnect: ToggleIcon(Iconsax.link, Iconsax.link_copy),
    yoyoWave: ToggleIcon(Iconsax.like, Iconsax.like_copy),
    yoyoChat: ToggleIcon(Iconsax.message, Iconsax.message_copy),
    // Social tabs
    socialStumble: ToggleIcon(Iconsax.shuffle, Iconsax.shuffle_copy),
    socialFriends: ToggleIcon(Iconsax.people, Iconsax.people_copy),
    socialEvents: ToggleIcon(Iconsax.calendar, Iconsax.calendar_copy),
    socialPost: ToggleIcon(Iconsax.add_circle, Iconsax.add_circle_copy),
    // Shop tabs
    shopBrowse: ToggleIcon(Iconsax.bag, Iconsax.bag_copy),
    shopDeals: ToggleIcon(Iconsax.tag, Iconsax.tag_copy),
    shopSell: ToggleIcon(Iconsax.shop, Iconsax.shop_copy),
    shopMessages: ToggleIcon(Iconsax.message, Iconsax.message_copy),
    // Service FAB
    serviceVideo: ToggleIcon(Iconsax.play_circle, Iconsax.play_circle_copy),
    serviceDating: ToggleIcon(Iconsax.heart, Iconsax.heart_copy),
    serviceYoyo: ToggleIcon(Iconsax.global, Iconsax.global_copy),
    serviceSocial: ToggleIcon(Iconsax.people, Iconsax.people_copy),
    serviceShop: ToggleIcon(Iconsax.shop, Iconsax.shop_copy),
    // UI actions
    search: Iconsax.search_normal,
    close: Iconsax.close_circle,
    arrowBack: Iconsax.arrow_left,
    chevronRight: Iconsax.arrow_right,
    check: Iconsax.check,
    checkCircle: Iconsax.tick_circle_copy,
    moreHoriz: Iconsax.more,
    share: Iconsax.share,
    send: Iconsax.send,
    reply: Iconsax.forward,
    favoriteOutline: Iconsax.heart,
    favoriteFilled: Iconsax.heart_copy,
    bookmarkOutline: Iconsax.bookmark,
    bookmarkFilled: Iconsax.bookmark_copy,
    visibilityOn: Iconsax.eye,
    visibilityOff: Iconsax.eye_slash,
    starFilled: Iconsax.star_copy,
    chatBubbleOutline: Iconsax.message,
    chatOutline: Iconsax.sms,
    forum: Iconsax.message_2,
    comment: Iconsax.message_copy,
    edit: Iconsax.edit,
    editOutline: Iconsax.edit_2,
    settings: Iconsax.setting,
    notifications: Iconsax.notification_copy,
    notificationsOutline: Iconsax.notification,
    personOutline: Iconsax.user,
    personAdd: Iconsax.user_add,
    personRemove: Iconsax.user_minus,
    storefront: Iconsax.shop_copy,
    storefrontOutline: Iconsax.shop,
    add: Iconsax.add,
    addCircle: Iconsax.add_circle,
    addPhoto: Iconsax.camera,
    photoLibrary: Iconsax.gallery,
    cameraAlt: Iconsax.camera,
    cameraAltOutline: Iconsax.camera,
    videocam: Iconsax.video,
    flipCamera: Iconsax.camera,
    timerOutline: Iconsax.timer,
    timerFilled: Iconsax.timer_copy,
    flashOn: Iconsax.flash,
    flashOff: Iconsax.flash_slash,
    speedOutline: Iconsax.forward,
    playArrow: Iconsax.play,
    playCircleOutline: Iconsax.play_circle,
    contentCut: Iconsax.scissor,
    textFields: Iconsax.text,
    emojiEmotions: Iconsax.emoji_happy,
    filterVintage: Iconsax.star,
    tag: Iconsax.tag,
    flag: Iconsax.flag,
    lockOutline: Iconsax.lock,
    blockOutline: Iconsax.close_square,
    phoneOutline: Iconsax.call,
    emailOutline: Iconsax.sms,
    locationOff: Iconsax.location_slash,
    tune: Iconsax.slider,
    filterList: Iconsax.filter,
    refresh: Iconsax.refresh,
    radar: Iconsax.radar,
    localOffer: Iconsax.tag_copy,
    localOfferOutline: Iconsax.tag,
    shoppingBag: Iconsax.bag_copy,
    gavel: Iconsax.judge,
    localFireDepartment: Iconsax.flash_copy,
    campaign: Iconsax.notification_copy,
    locationOn: Iconsax.location_copy,
    nearMe: Iconsax.map,
    group: Iconsax.people_copy,
    groupOutline: Iconsax.people,
    peopleOutline: Iconsax.people,
    wavingHand: Iconsax.like,
    image: Iconsax.image,
    verified: Iconsax.tick_circle_copy,
    calendarToday: Iconsax.calendar,
    linkIcon: Iconsax.link,
    linkOutline: Iconsax.link_1,
    replay: Iconsax.repeat,
    height: Iconsax.ruler,
    schoolOutline: Iconsax.teacher,
    localBarOutline: Iconsax.cup,
    workOutline: Iconsax.briefcase,
    viewList: Iconsax.menu,
  );
}
